### ISSUE TITLE
Memory usage increases massively after first panic

### ISSUE THREAD

**Issue by Diggsey** [getsentry/sentry-rust#102]
We're using sentry's panic handler in our applications, and we're experiencing a problem where the memory usage (resident set size) increases to anywhere from ~100MB to ~600MB after a panic occurs. (A panic kills the current request/work item, but not the whole application).

Unfortunately I haven't been able to fully determine the cause yet, but I know this much:
- The memory usage only increases when sentry is configured with a valid DSN. Just having the panic handler installed is not enough.
- The memory usage does not seem to increase further after additional panics.
- Generating a backtrace manually with backtrace-rs does not cause any noticeable increase in memory usage.
- The issue occurs in all of our services using sentry, and the amount of memory used seems to vary by service, but is fairly consistent within each type of service.
- The issue occurs on linux, for both musl and non-musl targets.
- The issue occurs with all possible sentry features disabled other than those needed to support the panic handler and the client.

I'm still working to identify where the allocation is coming from.

**Comment by Diggsey** [comment]
Hmm, even more confusingly, valgrind still shows only ~1.5MB of peak memory usage, whilst the same process has >100MB of resident set in procfs.

**Comment by Diggsey** [comment]
I was able to get it to show up in valgrind using:
`valgrind --tool=massif --time-unit=B --pages-as-heap=yes <binary>`

This shows it leaking exactly 128MB of memory each panic, so in fact the memory usage is increasing, but only a subset stays resident.

```
    GB
1.276^                                                                     #
     |                                                                     #:@
     |                                                              ::  :::# @
     |                                                              : :::  # @
     |                                                           :::: : :  # @
     |                                                       :::::  : : :  # @
     |                                                   ::::: : :  : : :  # @
     |                                               :::::   : : :  : : :  # @
     |                                            :::: : :   : : :  : : :  # @
     |                                        :::::  : : :   : : :  : : :  # @
     |                                 :: ::::: : :  : : :   : : :  : : :  # @
     |                                 : ::   : : :  : : :   : : :  : : :  # @
     |                           ::::::: ::   : : :  : : :   : : :  : : :  # @
     |                       ::::: :   : ::   : : :  : : :   : : :  : : :  # @
     |                    @@@:   : :   : ::   : : :  : : :   : : :  : : :  # @
     |                    @  :   : :   : ::   : : :  : : :   : : :  : : :  # @
     |            @@  ::::@  :   : :   : ::   : : :  : : :   : : :  : : :  # @
     |       ::   @ :::   @  :   : :   : ::   : : :  : : :   : : :  : : :  # @
     |       : :::@ : :   @  :   : :   : ::   : : :  : : :   : : :  : : :  # @
     |  :::::: :  @ : :   @  :   : :   : ::   : : :  : : :   : : :  : : :  # @
   0 +----------------------------------------------------------------------->GB
     0                                                                   2.470

Number of snapshots: 52
 Detailed snapshots: [7, 13, 46 (peak), 49]

--------------------------------------------------------------------------------
  n        time(B)         total(B)   useful-heap(B) extra-heap(B)    stacks(B)
--------------------------------------------------------------------------------
  0     19,476,480       19,476,480       19,476,480             0            0
  1     83,111,936       83,103,744       83,103,744             0            0
  2    128,786,432      128,720,896      128,720,896             0            0
  3    263,004,160      262,938,624      262,938,624             0            0
  4    279,785,472      246,157,312      246,157,312             0            0
  5    332,222,464      197,939,200      197,939,200             0            0
  6    466,440,192      332,156,928      332,156,928             0            0
  7    466,440,192      332,156,928      332,156,928             0            0
100.00% (332,156,928B) (page allocation syscalls) mmap/mremap/brk, --alloc-fns, etc.
->61.88% (205,553,664B) 0x5EB5A12: mmap (mmap64.c:52)
| ->60.61% (201,326,592B) 0x5E2AC87: new_heap (arena.c:487)
| | ->60.61% (201,326,592B) 0x5E2BA5A: arena_get2.part.3 (arena.c:692)
| |   ->60.61% (201,326,592B) 0x5E3054B: tcache_init.part.4 (arena.c:879)
| |     ->60.61% (201,326,592B) 0x5E311C9: malloc (malloc.c:2983)
| |       ->60.61% (201,326,592B) 0x596C513: pthread_getattr_np (pthread_getattr_np.c:176)
| |         ->60.61% (201,326,592B) 0xFA133F: std::sys::unix::thread::guard::current (thread.rs:395)
| |           ->40.41% (134,217,728B) 0xBC4E51: std::thread::Builder::spawn::{{closure}} (mod.rs:406)
| |           | ->40.41% (134,217,728B) 0xBC60CA: <F as alloc::boxed::FnBox<A>>::call_box (boxed.rs:672)
| |           |   ->40.41% (134,217,728B) 0xFA214C: std::sys_common::thread::start_thread (boxed.rs:682)
| |           |     ->40.41% (134,217,728B) 0xF92024: std::sys::unix::thread::Thread::new::thread_start (thread.rs:90)
| |           |       ->40.41% (134,217,728B) 0x596A6D9: start_thread (pthread_create.c:463)
| |           |         ->40.41% (134,217,728B) 0x5EBB88D: clone (clone.S:95)
```

**Comment by Diggsey** [comment]
On further investigation, it looks like it is the backtrace generation which is causing the permanent increase in memory usage. For some reason I haven't been able to reproduce it using backtrace-rs directly yet.

I think the valgrind "memory leak" must be spurious and unrelated - something to do with pthreads...

**Comment by Diggsey** [comment]
The issue seems to be caused by simply including sentry in a project - pulling in sentry increases the size of the debug symbols by ~50MB.

Example program to reproduce:
```rust
use std::thread;
use std::time::Duration;
use std::panic;

use backtrace::Backtrace;
use failure;
use url;
use log;
use sentry_types;
use env_logger;
use reqwest;
use lazy_static;
use regex;
use error_chain;
use im;
use libc;
use hostname;
use rand;
use httpdate;
use uname;
//use sentry;


fn main() {
    loop {
        println!("{:?}", Backtrace::new());

        thread::sleep(Duration::from_millis(100));
    }
}
```

This program pulls in all of the same dependencies as sentry itself, and compiles to a program with size 4.6MB. When I uncomment the `use sentry` line, the program size increases to 48MB.

When I run `strip` on the two binaries, they are both cut down to 643kB, so it's clear that the size increase is due to the debug symbols.

Note: in both programs, none of the code is actually called, so I would expect it all to be stripped away.

**Comment by mitsuhiko** [comment]
Thanks. I will have a look at this.

**Comment by Diggsey** [comment]
@mitsuhiko I don't think this is actually sentry's fault, it seems to be just an issue with debug symbols and rust, and the fact that sentry pulls in a lot of dependencies - the feature in #103 of separating the debug symbols is probably the best immediate fix.

It was exacerbated by a separate rustc bug with incremental compilation which caused the debug symbols to still be present in the final binary after I'd removed the code which actually initialised the sentry client.  (When I do a *clean* build which doesn't initialise the client but *does* `use sentry` the extra debug symbols go away).

Other than that, I found the unstable cargo profiles feature which lets you turn off debug info for dependencies, and helps reduce the debug symbols a bit, but not nearly as much as expected, to the point that it was still using an unreasonable amount of memory.

**Comment by mitsuhiko** [comment]
I'm going to close this for now. Not sure I can do much here *at the moment*. I will revisit this however.

**Comment by Diggsey** [comment]
In case anyone has the same issue, we did solve it by splitting the debug info from the binary and uploading it separately to sentry, and this works very well.
