### ISSUE TITLE
Feature: separate debug symbols

### ISSUE THREAD

**Issue by Diggsey** [getsentry/sentry-rust#103]
Enabling debug symbols massively increases the binary size, and also results in *very* high memory usage to load in those symbols when generating a backtrace (600MB in some cases). It would be useful there was a way to upload debug symbols separately, directly to sentry, and then have sentry do the symbol resolution.

**Comment by mitsuhiko** [comment]
This is already possible. You can upload the debug symbols (DWARF and breakpad are supported) to sentry and we symbolicate there. You just need to enable the `with_debug_meta` flag and server side symbolication should work.

**Comment by mitsuhiko** [comment]
For uploading debug files use `sentry-cli upload-dif`.

**Comment by Diggsey** [comment]
Oh awesome, I'll try that.
