### ISSUE TITLE
Memory usage constantly increasing in plain scenario using a background actor

### ISSUE THREAD

**Issue by vmalloc** [getsentry/sentry-rust#108]
I managed to reduce the reproduction code to the following:
```rust
use actix::prelude::*;
use actix_web::{server, App, HttpRequest};
use sentry_actix::SentryMiddleware;
use std::env;


pub struct AppState {}

impl AppState {
    pub fn init() -> AppState {
        AppState {}
    }
}


pub struct SampleActor {}

impl SampleActor {
    pub fn init() -> SampleActor {
        SampleActor {}
    }
}

impl Actor for SampleActor {
    type Context = Context<Self>;
}

pub fn render(_req: &HttpRequest<AppState>) -> String {
    "Hello there!".into()
}


fn main() {
    let _guard = sentry::init(env::var("SENTRY_DSN").ok());
    env::set_var("RUST_BACKTRACE", "1");
    sentry::integrations::panic::register_panic_handler();

    let system = System::new("system");

    let _actor = SampleActor::init().start();

    let server = server::new(move || {
        App::with_state(AppState::init())
            .middleware(SentryMiddleware::new())
            .resource("/metrics", |r| {
                r.get().f(render);
            })
    })
    .bind(("0.0.0.0", 8888))
    .expect("Cannot bind listening port");

    server.system_exit().start();
    system.run();
}
```

Running this and hammering the `/metrics` route causes memory to keep bloating with no apparent end. 

I'm not sure the problem is actually sentry-rust, but when I remove it the bloat stops...

**Comment by mitsuhiko** [comment]
Thanks. I will investigate this.

**Comment by vmalloc** [comment]
Just adding a small bit of information - disabling the Sentry middleware solves it, so I'm guessing the problem is there somewhere, and not, say, in the panic handler or something else.

**Comment by mitsuhiko** [comment]
Ah yeah. And on second though that's no surprise because the hub is stored on the actix request and before send hook has a circular dependency back to the request. Sadly I do not see a way to get a weak reference to an actix request. I will need to think of something for how to break that cycle.

**Comment by vmalloc** [comment]
Why does it only happen with another actor though? Doesn't seem to reproduce without it

**Comment by mitsuhiko** [comment]
@vmalloc i wonder if this bug disappears if you change `Arc::new(Hub::new_from_top(Hub::current()))` to `Arc::new(Hub::new_from_top(Hub::main()))` in the `new_hub` method in sentry-actix.

**Comment by vmalloc** [comment]
I will try to check it later. Not sure I know how to work with a checked-out version of `sentry-actix` locally though

**Comment by mitsuhiko** [comment]
```toml
[patch.crates-io]
sentry-actix = { path = "/path/to/checkout/of/getsentry/sentry-rust }
```

In your `Cargo.toml`. It will auto discover the nested module in the repo.

**Comment by vmalloc** [comment]
👍 will give it a try a bit later

**Comment by vmalloc** [comment]
Nope - still happening after the patch you suggested...

**Comment by mitsuhiko** [comment]
I'm getting closer to the issue though. I tried to push and pop a dummy scope now and it fails to pop because something else is on top. Investigating this.

**Comment by mitsuhiko** [comment]
Pushed a fix for this. Was indeed a cycle.

**Comment by vmalloc** [comment]
@mitsuhiko Thanks! Will there be a new version on crates.io containing the fix soon?

**Comment by mitsuhiko** [comment]
Need to fix master and fix two more bugs, then i will push it. Hopefully I can do it today/tomorrow.

**Comment by vmalloc** [comment]
@mitsuhiko I see. Thanks!
