### ISSUE TITLE
log4rs handle support

### ISSUE THREAD

**Issue by tylerhawkes** [getsentry/sentry-rust#111]
I'd like to be able to use sentry with log4rs while still being able to change the log4rs config. Currently I'm using log4rs and I dynamically reload the config whenever the file changes using inotify. To do this, the init function of log4rs returns a handle that I keep in a static mut. After looking at the examples and the code, I don't see how that's possible right now since the init call doesn't return anything. I'm happy to use any workarounds that might be available.

**Comment by bbigras** [comment]
How do you use log4rs with sentry? With `sentry::integrations::log`? Do you have an example?

**Comment by mitsuhiko** [comment]
You could make a proxy I assume. Sentry's log integration just dispatches to another logger.

**Comment by tylerhawkes** [comment]
We don't use it yet, but are considering it. Even just an example of how to use it with something other than env logger would be great.

**Comment by msrd0** [comment]
I'd like to see something with rust/log4rs similar to java/logback, where I can add sentry as an appender that will upload all messages with warn level or higher. Code could look similar to this:

```rust
let sentry = SentryAppender::builder()
		// ...
		.build();
	
let config = Config::builder()
		// ...
		.appender(Appender::builder().build("sentry", Box::new(sentry)))
		// ...
		.build(Root::builder().appender("sentry").build(LevelFilter::Warn))
		.unwrap();
```

**Comment by msrd0** [comment]
I've now made https://crates.io/crates/log4rs-sentry to get the desired behaviour

**Comment by szokeasaurusrex** [comment]
We are currently doing a cleanup of old issues. Since the last activity on this issue was more than five years ago, I am assuming it is likely no longer relevant, so I am closing it for now. Please raise a new issue if this issue is still relevant.
