### ISSUE TITLE
Allow any string in the ClientOptions release

### ISSUE THREAD

**Issue by ilari-makimattila** [getsentry/sentry-rust#133]
We are using Sentry to track errors in several services, written in various languages like JavaScript and Python. In every service we set the release as the commit from which the the deployed package was built. It works fine in every project except the ones implemented in Rust.

The web page tells that it's ignoring an invalid value in the release field:
![image](https://user-images.githubusercontent.com/1040612/54214139-f9c2bf00-44e5-11e9-92f8-ff4f6cf85312.png)

Again this works as expected with the python client:
![image](https://user-images.githubusercontent.com/1040612/54214235-270f6d00-44e6-11e9-8d25-5ce8d36f8d62.png)

Could you relax the constraints for the Rust client so we can get the same experience across all projects?

**Comment by rye** [comment]
Looking at the below docstring, it certainly seems to be the case that the client expects something of the form that could be generated by `format!("{}@{}", env!("CARGO_PKG_NAME"), env!("CARGO_PKG_VERSION"))` but that doesn't help in this case.

https://github.com/getsentry/sentry-rust/blob/8af14ea7078e7c521f0b413f78680e5eb17ff142/src/client.rs#L632-L644

It certainly seems like this is a server-side issue, not a client-side issue, as the client doesn't perform validation.  I'm not super familiar with this, but out of curiosity have you tried `<crate name>@<commit sha>` as a release value? I wonder if it would take that.

**Comment by ilari-makimattila** [comment]
I took a look at the Python client code and noticed that it trims whitespace from several variables: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/client.py#L127-L129

The Rust client doesn't seem to do that and in fact the release is reported correctly in the UI after I added `.trim()` to the release value.

Would it make sense for the Rust client to do the same?

**Comment by rye** [comment]
Good find! I think so, personally, given that other clients do the same. 

I.a. the Ruby client happens to actually do its [own detection magic](https://github.com/getsentry/raven-ruby/blob/284e39422068b3f3b1b1223a5b43dd6c756c9397/lib/raven/configuration.rb#L349-L355), which also strips whitespace.

(I could foresee someone grabbing the output from `git rev-parse HEAD` and accidentally including the newline.)

Rust could totally do this. I'll be happy to PR that.

**Comment by jan-auer** [comment]
@untitaker Looks like this is a candidate for server-side normalization. Reading the release from some environment or file seems to happen very often and so far every SDK had to provide a workaround for this.

**Comment by untitaker** [comment]
See https://github.com/getsentry/semaphore/pull/184 which just strips this on the server.

**Comment by mitsuhiko** [comment]
I'm going to close this here as this is not an SDK issue and the server trims now.
