### ISSUE TITLE
Add sentry features to sentry-actix?

### ISSUE THREAD

**Issue by repi** [getsentry/sentry-rust#139]
Possible to add the sentry features for `sentry-actix`'s usage of sentry main crate as well? 

Primarily after being able to configure it also to use `rustls` but likely should just propagate all features?

**Comment by mitsuhiko** [comment]
Good point. Changed this in 80f92461a4ddcd36ee9856e1a4702f2f7fd1cbed

**Comment by repi** [comment]
Thanks!
