### ISSUE TITLE
Rate limit by event kind

### ISSUE THREAD

**Issue by Diggsey** [getsentry/sentry-rust#140]
Sometimes a problem can cause a sudden flood of events, and if we're not careful it can eat into our sentry quota very rapidly.

It would be useful to be able to rate-limit by event type in the client. Ideally I would configure a limit per hour, eg. "max 60 events of each type per hour", and then in sentry I would first get the 60 "normal" events, but once I hit that threshold, I would just get a single "error X is still happening" event at a rate of once per hour until it falls below the threshold.

**Comment by Swatinem** [comment]
Actually the sentry server has gained support for reporting more fine grained rate limits per event category, which needs to be added to the SDK as well.

**Comment by Swatinem** [comment]
I added new rate limiting functionality in `0.23.0` implementing the new rate limits that relay sends. If you need more fine-grained control, you would need to use the `before_send` hook.
