### ISSUE TITLE
Failure integration should properly handle `failure::err_msg`

### ISSUE THREAD

**Issue by Ten0** [getsentry/sentry-rust#144]
When sending a `failure::err_msg` through the `failure` integration, all the events are stacked as `ErrorMessage` even if the error messages are different. They should instead be stacked on the actual error message.

**Comment by Swatinem** [comment]
I think this is rather a serverside concern, and as far as I read the relevant docs, the error message should actually separate these two.
There is some guides around customization of grouping. You can define a custom `before_send` callback and customize the fingerprint.
https://docs.sentry.io/guides/grouping-and-fingerprints/
https://docs.sentry.io/data-management/event-grouping/

I will close this for now, please re-open if it is still an issue.
