### ISSUE TITLE
Any example for `sentry_setup` in a separate function returning the `ClientInitGuard` ?

### ISSUE THREAD

**Issue by suvash** [getsentry/sentry-rust#150]
Context:
I'm currently writing a CLI application, though it should not be any different for a long running process. I like to have a separate function in my main entry function that takes care of various setup things, for eg. args/config. parsing, logging setup etc. 
In similar interests, I'd like to have a function that wraps over all the setup things needed for sentry reporting. From what I've seen in the documenation, the `sentry::init(..)` and variants produce a `sentry::client::ClientInitGuard`, which when goes out of scope flushes all the remaining messages.

Issue:
So, I set out to write a function that would return the `ClientInitGuard` (which could be kept around in the main scope), but it seems like this is not possible, as the `sentry::client` is a private module. I found a way to solve this by returning a type that implemented Drop, which I think is a *very* hacky solution. I have a couple of questions that I'd very much appreciate if answered.

Code:
```rust
    // somewhere inside main()
    let sentry_dsn = Some("https://sentry.url/thing"); // from config/arg parsing hence Option
    let maybe_sentry = setup_sentry_client(sentry_dsn);
```

```rust
pub fn setup_sentry_client(maybe_sentry_dsn: Option<String>) -> Option<impl Drop> {
    log::trace!("attempting sentry client setup");
    let sentry_options = sentry::ClientOptions {
        release: sentry::release_name!(),
        ..Default::default()
    };

    let maybe_client = match maybe_sentry_dsn {
        Some(sentry_dsn) => {
            let client = sentry::init((sentry_dsn, sentry_options));
            log::info!("sentry client initialized");
            Some(client)
        }
        None => {
            log::info!("no sentry dsn provided : sentry client not initialized");
            None
        }
    };
    maybe_client
}
```
Questions:
- I'm rather new to Rust, so maybe it's something very simple that I'm missing. How do I simply return the correct type (ClientInitGuard) from a setup function ? without the `impl Drop` return trait.
- If that's not possible, I'm curious as to why `sentry::client::ClientInitGuard` is not public ?

**Comment by jan-auer** [comment]
Hi @suvash, `ClientInitGuard` is public, but it is exported from a different namespace: `sentry::internals`. You can find it [here](https://docs.rs/sentry/0.15.5/sentry/internals/struct.ClientInitGuard.html).

You can also just pass the `None` DSN through to `sentry::init`. It will skip initialization of the client and return a noop wrapper that efficiently skips all internal actions. That way, you don't have to deal with `None` outside of this function.

Your full example would then look like this:

```rust
use sentry::ClientOptions;
use sentry::internals::ClientInitGuard;

pub fn setup_sentry_client(dsn: Option<String>) -> ClientInitGuard {
    let sentry_options = ClientOptions {
        release: sentry::release_name!(),
        ..ClientOptions::default()
    };

    sentry::init((dsn, sentry_options))
}
```

**Comment by suvash** [comment]
Ah, I see. Thanks a lot for the answer. Hopefully, I get better at finding these over time. 🍻

**Comment by jan-auer** [comment]
> Hopefully, I get better at finding these over time.

On rustdoc, you can just navigate to types by clicking on them (they contain links). For instance, on the documentation of the [`sentry::init`](https://docs.rs/sentry/0.15.5/sentry/fn.init.html) function, just click the return type in the type signature and it takes you straight to the place where it is declared.

> 🍻

🥂
