### ISSUE TITLE
Lack of support for `std::error::Error`

### ISSUE THREAD

**Issue by kornelski** [getsentry/sentry-rust#151]
I'm surprised that there's a convenience function for `failure::Error`, but not for the standard library equivalent.

`std::error` doesn't have a backtrace, but it does have a chain of `source()` errors. And the `source()` method supports downcasting, so it could automatically pick up `failure::Error` and others in the chain.

**Comment by jan-auer** [comment]
This is indeed an issue and we can look into supporting that. We're currently working on getting backtraces into the standard library, but I agree that in the meanwhile it might be nice to at least have partial support for `std::error::Error`. 

However, downcasting won't work as well in this case. Ideally, one would try to downcast to any `E: failure::Error`, but that's not possible. Probably the best way would be to report the error without a stack trace in that case.
