### ISSUE TITLE
Is it possible to use the `Dsn` type from the sentry-types crate?

### ISSUE THREAD

**Issue by maxcountryman** [getsentry/sentry-rust#154]
I'd like to be able to do something like this:

```
let _guard = sentry::init(my_sentry_dsn);
```

Where `my_sentry_dsn ` is a `sentry_types::Dsn`. However this won't work, because there's no implementation of `From<Client>` for `Dsn`.

**Comment by jan-auer** [comment]
This is fixed on master as long as you're using the same version of `sentry-types`, or `sentry::internal::Dsn`. Thanks!
