### ISSUE TITLE
<unknown> frames in Lambda custom runtime

### ISSUE THREAD

**Issue by maxcountryman** [getsentry/sentry-rust#157]
Hello,

We're publishing a small set of Rust-based Lambda functions using the [serverless-rust](https://github.com/softprops/serverless-rust) plugin for Serverless.

In order to gain better visibility into our functions we've setup and enabled this plugin, however in the Lambda production environment, and only there, we're seeing an issue where frames are showing up without line numbers and named "<unknown>"; practically this makes the exception logging nearly worthless.

Interestingly enough, the same code compiled in a Docker container (the same container used to build the binary that's shipped to AWS) sends frames to Sentry as expected, with full context and properly named.

In the production environment, we've verified that things like `RUST_BACKTRACE` are set as expected to `1`.

We've been back and forth with your support and they ultimately directed us here--there's some information I can't share on a public forum, but if you can refer to that original ticket we've provided extensive documentation, including the source code, which can be used to reproduce this problem.

<img width="640" alt="Screen Shot 2019-09-18 at 11 27 20 AM" src="https://user-images.githubusercontent.com/74351/65175251-6378d400-da07-11e9-86e0-0a8a1d104264.png">

**Comment by jan-auer** [comment]
I believe this has been solved in the meanwhile, feel free to reopen if this issue still occurs.
