### ISSUE TITLE
anyhow integration

### ISSUE THREAD

**Issue by repi** [getsentry/sentry-rust#162]
[`anyhow`](https://github.com/dtolnay/anyhow) is a great, small and clean `failure` create replacement that was released very recently, would be great to have a sentry integration for it. 
Probably can use the `failure` one as a base.

We are currently testing to transition from `failure` to `anyhow` to have a simpler library that implements `std::error::Error`

**Comment by Swatinem** [comment]
> to `anyhow` to have a simpler library that implements `std::error::Error`

too bad anyhow does not actually implement `std::error::Error`. Would have been really straightforward otherwise.

This was implemented in #212 but I still have some cleaning up to do before I can cut a release.
