### ISSUE TITLE
can't get debug symbols working (symbolicated)

### ISSUE THREAD

**Issue by Roger** [getsentry/sentry-rust#164]
I'm trying this with the example to configure sentry, uploading debug symbols using sentry-cli, the result in sentry ui is:
![image](https://user-images.githubusercontent.com/9746/67012477-c38b9480-f0f1-11e9-95c0-3edc902ceace.png)

**What am I doing:**
```
[roger@skaro] $ cargo build --release
[roger@skaro] $ cd target/release/
[roger@skaro] $ sentry-cli upload-dif -p rust-test --org org sentry-test
> Found 1 debug information file
> Prepared debug information file for upload
> Uploaded 1 missing debug information file
> File processing complete:

     OK 25836fb8-17d5-38e5-d5cb-bd5bf6df6108 (sentry-test; x86_64 library)
[roger@skaro] $ strip sentry-test
[roger@skaro] $ ./sentry-test
thread 'main' panicked at 'BOOM', src/main.rs:5:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
zsh: exit 101   ./sentry-test
[roger@skaro] $ sentry-cli difutil id sentry-test
25836fb8-17d5-38e5-d5cb-bd5bf6df6108
```

**Comment by amircodota** [comment]
@Roger I think I figured it out.

You need to change your release profile [to include debug symbols](https://stackoverflow.com/questions/38803760/how-to-get-a-release-build-with-debugging-information-when-using-cargo).

The binary will be much bigger - so after you upload the debug info, you need to strip it.

**Comment by jan-auer** [comment]
> You need to change your release profile [to include debug symbols](https://stackoverflow.com/questions/38803760/how-to-get-a-release-build-with-debugging-information-when-using-cargo).

This is it. You can check this with `sentry-cli difutil check path/to/file`. If it shows "debug", then you'll be all set.

**Comment by Roger** [comment]
oh, thanks! I'll try this soon and I'll give you some feedback

**Comment by jan-auer** [comment]
For some reason, I thought we had that documented already. I'll keep this issue open until we've added it in an appropriate place.
