### ISSUE TITLE
Update sentry-actix to work with latest actix-web

### ISSUE THREAD

**Issue by gabelerner** [getsentry/sentry-rust#187]
It's currently pinned to `0.7`
https://github.com/getsentry/sentry-rust/blob/master/integrations/sentry-actix/Cargo.toml#L30

`actix-web` is up to `2.0.0`

Because the `actix_web::middleware::Middleware` trait is gone, I can't even compose the old version into the new one. Example that fails:
![image](https://user-images.githubusercontent.com/241819/77831651-b4236500-70ed-11ea-9f5b-cf8341faf619.png)

**Comment by onelson** [comment]
I suspect nothing has changed to resolve the blockers identified in !143. Most of the difference between actix-web 1.0 and 2.0 came in the transition to async/await.

**Comment by gabelerner** [comment]
you're right, i will close and wait for that one!
