### ISSUE TITLE
Random segmentation fault when a panic is called in a tide request handler.

### ISSUE THREAD

**Issue by qdequele** [getsentry/sentry-rust#188]
I had a segmentation fault when I tried to add Sentry to my project. https://github.com/meilisearch/meilisearch

I have noticed that the segmentation fault appears when I call a `panic!` into one of my [tide](https://github.com/http-rs/tide) request handler. 

To simplify the debug, I have created a new repository to create a minimal reproducible project. https://github.com/qdequele/test-sentry I also add an [lldb backtrace file](https://github.com/qdequele/test-sentry/blob/master/export-lldb.txt), but I explain in the readme all the step to reproduce the segmentation fault.

Apparently, it's from using the backtrace library.  I'll let you be the judge of that, but if I can help, I'd be happy to.

**Comment by Swatinem** [comment]
Now that `backtrace` is using gimli by default, I think we can close this?
