### ISSUE TITLE
panic! prevent crate to send events

### ISSUE THREAD

**Issue by cyrilchampier** [getsentry/sentry-rust#21]
I tried several way to enable panics to be sent to sentry, without success.
If I do something wrong, please point it to me.

# simple panic
```
    let credential: SentryCredential = SENTRY_KEY.parse().unwrap();
    let sentry_client = Sentry::new("machine_name".to_owned(), "version".to_owned(), "env".to_owned(), credential);
    sentry_client.debug("", "panic handler NOT pluged", None);
    println!("before panic");
    panic!("bim panic");
```
output:
```
before panic
thread 'main' panicked at 'bim panic', src/bin/kragle.rs:89
```
and nothing is sent to sentry

# with panic handler
I tried with a panic handler, no luck either:
```
    let credential: SentryCredential = SENTRY_KEY.parse().unwrap();
    let sentry_client = Sentry::new("machine_name".to_owned(), "version".to_owned(), "env".to_owned(), credential);
    sentry_client.register_panic_handler(Some(|panic_info: &PanicInfo| -> () {
        println!("je PANIC");
    }));
    sentry_client.debug("", "panic handler pluged", None);
    println!("before panic");
    panic!("bim panic");
```
outputs:
```
before panic
je PANIC
```
still nothing sent to sentry

# without panic
of course, if i simply start sentry and send something, everything is fine:
```
    let credential: SentryCredential = SENTRY_KEY.parse().unwrap();
    let sentry_client = Sentry::new("machine_name".to_owned(), "version".to_owned(), "env".to_owned(), credential);
    sentry_client.error("", "panic handler NOT pluged", None);
    println!("no panic");
```
outputs
```
no panic
```
and in sentry I get the correct event "panic handler NOT pluged"

**Comment by cyrilchampier** [comment]
# with a sleep in panic handler

```
    let credential: SentryCredential = SENTRY_KEY.parse().unwrap();
    let sentry_client = Sentry::new("machine_name".to_owned(), "version".to_owned(), "env".to_owned(), credential);
    sentry_client.register_panic_handler(Some(|panic_info: &PanicInfo| -> () {
        use std::thread::sleep;
        use std::time::Duration;
        sleep(Duration::from_millis(1000));
        println!("je PANIC");
    }));
    sentry_client.debug("", "panic handler OK pluged", None);
    panic!("bim panic");
```
outputs
```
je PANIC
```
and send event `panic handler OK pluged` to sentry.
but still no `bim panic`

**Comment by cyrilchampier** [comment]
# with a sleep of 3 seconds in panic handler
well... both "debug" and "fatal" logs are sent to sentry.
i also discov ered that a 1 second wait is sufficient to send the "fatal" if i comment the "debug"...

**Comment by aagahi** [comment]
coz your program exits before sending the message.

**Comment by adaedra** [comment]
That's the conclusion we got too, hence the addition of more sleeps. But that's hardly ideal, and means the crate can't be used directly to handle panics (most of the time, panics will lead to program termination). Sleeps are also hardly ideal, as we don't know which amount of time to wait for.

The ideal would be to implement a wait for the response from sentry, like the [sentry-rs](https://crates.io/crates/sentry-rs) does. This way, we are sure that panics are correctly handled in the application, which is what the crate in its current state fails to ensure.

**Comment by aagahi** [comment]
Feel free to propose a PR according to the sentry-rs fork.
