### ISSUE TITLE
Panic + deadlock when using LLD 10.0.0

### ISSUE THREAD

**Issue by Jake-Shadle** [getsentry/sentry-rust#220]
I'm not sure when this was changed, so it might apply to more LLD's than just 10.0.0, but it appears that LLD now uses xxhash to compute the build ID stored in `.note.gnu.build-id` instead of ld's usual sha1. This causes a panic [here](https://github.com/getsentry/sentry-rust/blob/b66352a0a30a5da5f6aef0f25e29f8024e7bc3e0/sentry-debug-images/src/unix.rs#L17), as the section is only 8 bytes instead of 20, so the slice panics, and since this code is usually already being called from a panic handler, we end up in a deadlock waiting for the `Once` in `Client::capture_event`.

**Comment by Jake-Shadle** [comment]
For now I'm working around this by forcing LLD to use sha1 when calculating the build id, as this probably won't be a simple fix.

```ini
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-Wl,--build-id=sha1",
]
```

**Comment by Swatinem** [comment]
Thats interesting. We basically do the same on native:

https://github.com/getsentry/sentry-native/blob/9871bf8109a23850d29ff20dfb97c5bffbaf9446/src/modulefinder/sentry_modulefinder_linux.c#L287

Just with the difference that we do an unsafe read, because yolo, its C…

I think @jan-auer knows more about how to handle this, since our whole pipeline would need to handle these IDs.

**Comment by Jake-Shadle** [comment]
It might be that everyone else is correctly [reading your docs](https://docs.sentry.io/workflow/debug-files/#gnu-build-identifiers) and explicitly specifying the flag when using clang/lld, and I just got lucky. :wink:

**Comment by Swatinem** [comment]
Either way, we shouldn’t be panicking (or reading invalid memory) when the ID in the header is <16 bytes. Rather pad it with 0 or something. Not sure what the best idea would be in this case.

**Comment by jan-auer** [comment]
It needs to be padded with 0 to comply with breakpad. I can get a fix for this going.

**Comment by Jake-Shadle** [comment]
Thanks!
