### ISSUE TITLE
SSL link errors with sentry-rs?

### ISSUE THREAD

**Issue by maxburke** [getsentry/sentry-rust#227]
I’m trying to integrate Sentry with my (Rust) application but I keep getting SSL-related linker errors, such as:

```
  = note: /usr/bin/ld: /home/max/src/ul/services/target/debug/deps/libopenssl_sys-9d72d031aaceda91.rlib(openssl_sys-9d72d031aaceda91.openssl_sys.2sb60usr-cgu.7.rcgu.o): in function `openssl_sys::tls1::SSL_set_tlsext_host_name':
          /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.57/src/tls1.rs:46: undefined reference to `SSL_ctrl'
          /usr/bin/ld: /home/max/src/ul/services/target/debug/deps/libopenssl_sys-9d72d031aaceda91.rlib(openssl_sys-9d72d031aaceda91.openssl_sys.2sb60usr-cgu.9.rcgu.o): in function `openssl_sys::ssl::SSL_CTX_set_mode':
          /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.57/src/ssl.rs:415: undefined reference to `SSL_CTX_ctrl'
          /usr/bin/ld: /home/max/src/ul/services/target/debug/deps/libopenssl_sys-9d72d031aaceda91.rlib(openssl_sys-9d72d031aaceda91.openssl_sys.2sb60usr-cgu.9.rcgu.o): in function `openssl_sys::ssl::SSL_CTX_add_extra_chain_cert':
          /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.57/src/ssl.rs:766: undefined reference to `SSL_CTX_ctrl'
          /usr/bin/ld: /home/max/src/ul/services/target/debug/deps/libopenssl_sys-9d72d031aaceda91.rlib(openssl_sys-9d72d031aaceda91.openssl_sys.2sb60usr-cgu.9.rcgu.o): in function `openssl_sys::ssl::SSL_CTX_set_min_proto_version':
          /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.57/src/ssl.rs:824: undefined reference to `SSL_CTX_ctrl'
          /usr/bin/ld: /home/max/src/ul/services/target/debug/deps/libopenssl_sys-9d72d031aaceda91.rlib(openssl_sys-9d72d031aaceda91.openssl_sys.2sb60usr-cgu.9.rcgu.o): in function `openssl_sys::ssl::SSL_CTX_set_max_proto_version':
          /home/max/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.57/src/ssl.rs:833: undefined reference to `SSL_CTX_ctrl'
```

I’m using the sentry-0.18.1 crate, have SSL libraries and SDKs installed. I’ve tried both the native TLS feature as well as rustls and have had no success with either.

**Comment by jan-auer** [comment]
Which version of `openssl` is installed on the build system? 

Could you try to pull in the `openssl` library as a direct dependency and activate the [`vendored`](https://docs.rs/openssl/0.10.29/openssl/#vendored) feature as a workaround? I'm assuming that the installed library or headers are incompatible with what `openssl-sys` expects.

**Comment by maxburke** [comment]
I've seen it with 1.1.1f (system default with Ubuntu 20.04) and 1.1.1 (with Ubuntu 18.04).

Do you know why it's still trying to draw in openssl even if rustls is being used?

**Comment by Swatinem** [comment]
Just tried a few things:
I’m on arch, with `openssl@1.1.1g`, and `openssl-sys@0.9.58`, I can compile without any problems with the default features.

Speaking of features, those are *additive*, and the `with_default_transport` feature pulls in native-tls, aka openssl. You have to use `default-features = false, features = ["with_reqwest_transport", "with_rustls"]` to remove openssl from the dependencies.

Hope this helps. I don’t really know how to investigate this without being able to reproduce this.

**Comment by maxburke** [comment]
Hi @Swatinem 

After setting default-features to false it succeeds. Thank you!
