### ISSUE TITLE
Update README with new function signatures

### ISSUE THREAD

**Issue by Bckempa** [getsentry/sentry-rust#23]
Sentry::new() and Sentry::from_settings() had their call signatures changed in commit 5bb425588c61e340ffac2e795e9703a80ed37ea1 upgrading hyper and adding tokio to require a tokio_core::reactor::Handle. This usage is not present in the README examples and the current README examples won't compile.

This could be off-putting to a newcomer to Rust who may dig into the crate to find they need a tokio reactor, but now have to learn asynchronous networking in Rust just send a test Sentry message.

(I'm in this boat and am happy to submit a PR once I figure out if and how I want to integrate a tokio reactor into the project I was hoping to instrument with Sentry)

**Comment by Bckempa** [comment]
Ok, it was pretty easy to get working based off the tests, but a few modification had to be made like using the constructor for settings instead of directly specifying the fields:

**Comment by aagahi** [comment]
You're more that welcome to propose a PR. ty for your help

**Comment by yjh0502** [comment]
Maybe solved with https://github.com/getsentry/sentry-rust/pull/24?
