### ISSUE TITLE
Events in 0.19 get discarded

### ISSUE THREAD

**Issue by rideron89** [getsentry/sentry-rust#231]
When sending events using `capture_event` in v0.19, events seem to fail (and return a nil UUID) about 60% of the time.

If I switch to `capture_event` in 0.18, they seem to send closer to 100% of the time. No code changes were made.

Here is a skimmed down version of my code:

```rust
let _guard = sentry::init(config.SENTRY_DSN.as_str());

// ...

let message = "Something failed".to_string();

capture_event(Event {
    level: Level::Error,
    message: Some(message.clone()),
    ..Default::default()
});
```

I also noticed the issue seems to occur when using `capture_anyhow`, as well.

I checked my Sentry project settings, most are default, and nothing looks like it should be excluding anything.

Rust version: `cargo 1.44.1 (88ba85757 2020-06-11)`
Toolchain: `stable-x86_64-unknown-linux-gnu`

**Comment by Swatinem** [comment]
can you try turning on logging and see what happens?

**Comment by rideron89** [comment]
Naturally, events are sending just fine now. Sending the same events. I just sent about 15 events and they all went through.

I'll try again later to see if there really is an issue here, and post my logging if any fail to go through.

**Comment by rideron89** [comment]
I have had no issues since the original post.

I'm going to close this and chock whatever I was experiencing up to a temporary issue.

If I experience this again, I'll create a new ticket with more debugging information. Thanks!
