### ISSUE TITLE
New panic handler is not documented in the sentry crate

### ISSUE THREAD

**Issue by kornelski** [getsentry/sentry-rust#235]
It's hard to find documentation on replacement for `register_panic_handler()`

Documentation search: https://docs.rs/sentry/0.19.0/sentry/?search=panic finds https://docs.rs/sentry/0.19.0/sentry/integrations/panic/fn.panic_handler.html

but that function is just:

```rust
pub fn panic_handler(info: &PanicInfo)
```

but documentation doesn't have an example how this function is meant to be used. To me it looks like some internal callback, so I'm not sure if I'm supposed to install a panic hook myself.

The changelog says:

> * The integrations module was completely rewritten.

but there's no information how the new integrations look like.

**Comment by Swatinem** [comment]
The `PanicIntegration` is enabled by default:

https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry/src/defaults.rs#L15-L25

And it will set itself as the panic handler automatically on setup, so no need to do that manually:

https://github.com/getsentry/sentry-rust/blob/36218ea5e815d871c073ee15d7f71ee01dab69c7/sentry-panic/src/lib.rs#L55-L61

Does that sufficiently answer your question? Or what kind of documentation would make this clearer?

**Comment by kornelski** [comment]
Yes, thank you. Automatic is much better than I expected — I thought I'd have to write a replacement for the function that has been removed.
