### ISSUE TITLE
Unable to get example in README working

### ISSUE THREAD

**Issue by mcfilib** [getsentry/sentry-rust#25]
I'm trying out `sentry-rust` for a project at work and have added the example code from the README.md to our application. 

When I call `sentry.info("test.logger", "Test Message", None);` or `.error` in my code, I don't see anything in the Sentry dashboard. I expect to see something show up in the dashboard.

As I'm not too familiar with Sentry it might be that I'm doing something obviously wrong.

## Code

As you can see, I'm not doing anything different from the example in the README.md.

``` rust
    let core = Core::new().expect("failed to initialise event loop");
    let handle = core.handle();
    let creds = "{street_cred}"
        .parse::<SentryCredential>()
        .unwrap();

    let sentry = Sentry::from_settings(handle, Default::default(), creds);
    sentry.info("test.logger", "Test Message", None);
```

## Questions

- Am I doing something obviously wrong here?
  - If I am, could the docs be improved to avoid someone getting into a similar trap?
  - If I'm not, how do I debug this?

## Environment 

```
rustc: 1.22.0-nightly 
sentry: 0.2.0
tokio-core: 0.1.10
```

**Comment by onelson** [comment]
@filib I'm seeing the same, but assumed it was related to ssl cert verification failing (we use self-signed certs for all our internal stuff). 

On other sentry clients, they let you turn off the certificate verification step by adding `verify_ssl=0` to the dsn url, but there is no such option here (yet). I just tried disabling the verification in a fork to see if this was the culprit, but I'm still not having any luck.

Does this sound like your situation?

**Comment by aagahi** [comment]
Are you sire you program doesn't exit before sending the message?
Could you try with rustc stable?

**Comment by onelson** [comment]
@aagahi In my case, I'm certain the program is not exiting before the message is sent. It's a long running process (it's a rocket app). That said, rocket requires nightly, so maybe that's the issue?
I'm going to add some logging and try to trace through the call stack in the client code to see if I can find the break.

**Comment by filib** [comment]
It’s also a long running process in my case.

Unfortunately I’m also unable to test with stable. We ended up switching to a fork (https://github.com/SecurityInsanity/sentry-rs), which is working fine.

**Comment by onelson** [comment]
Oh nice. This one doesn't rely on a tokio event loop, which is a little more convenient when working in a framework that doesn't already rely on tokio. I'll give it a shot!

**Comment by onelson** [comment]
Yep that other crate works like a charm. It also had logging calls I could enable to see that the ssl validation was preventing my app from posting events to sentry. Rather than hacking the connection, I went and got a CA cert in place for the container I'm running in... 

I'm betting I could switch back to this crate now that I have the cert in place, but there are some nice bits to this other crate. Think I'll stick with the 3rd party for now.

**Comment by brandur** [comment]
I just dropped in to say that I experienced the same thing — everything seems to work, but nothing shows up on Sentry's end. In my case I don't think it's a certificate problem given that I'm using a similar setup to talk to other common HTTPS URLs just fine. I also tried adding a sleep statement after the sentry emit just in case it was a problem with the process exiting before it had a chance to send — still a no go. (Even if that had worked though, that's a hack that would've been bad enough to send me in the direction of another library.)

I'll also try https://github.com/SecurityInsanity/sentry-rs which people above seem to have had good luck with, but this kind of divergence is of course not a great place for the library to be — I'd rather be using an officially distributed library with better guaranteed longevity.

If there are any maintainers reading this thread, it might be nice to either see if some of the bugs/pitfalls could be repaired, or if no further work here is intended, maybe just change the README to a link to the fork.

**Comment by davechallis** [comment]
Also seeing the same issue (tested with stable Rust 1.23.0 and 1.24.0). Currently evaluating Sentry for a number of languages we use, Python and Java clients work great, but can't get anything to be sent using this client (it runs fine, but no issues show up in my Sentry account).

Unfortunately it's probably going to be a blocker for us adopting Sentry for our organisation, while the 3rd party client does work, we'd rather wait until there's an officially supported client.

**Comment by maciejkula** [comment]
FWIW it seems slightly troubling that the default behaviour on logging an event is to hand the task out to the Tokio reactor and silently drop the errors: https://github.com/getsentry/sentry-rust/blob/master/src/lib.rs#L287

**Comment by mcfilib** [comment]
@mitsuhiko has this been resolved?

**Comment by mitsuhiko** [comment]
@mcfilib the old client is deprecated. The new one will come by mid next week is the plan. Master already reflects the new client.

**Comment by bbigras** [comment]
Is it possible to use `verify_ssl=0` with the new client?
