### ISSUE TITLE
Soundness issues in dependency `sized-chunks` (via `im` crate)

### ISSUE THREAD

**Issue by GeorgeHahn** [getsentry/sentry-rust#258]
See https://github.com/bodil/sized-chunks/issues/11.

**Comment by dbrgn** [comment]
This also has a rustsec advisory: https://rustsec.org/advisories/RUSTSEC-2020-0041

Note that unfortunately there are no fixes so far.

**Comment by jan-auer** [comment]
This also relates to https://github.com/getsentry/sentry-rust/issues/257, suggesting that we run the audit action as part of CI. 

On a more direct note, this will require some closer investigation, as this is still open in `sized-chunks` and we rely heavily on `im`.

**Comment by Roguelazer** [comment]
Any update here? It's been three months and every project that uses `sentry` has unfixable rustsec advisories against it, which kind of unfortunate? The fact that the advisory causes memory safety issues during a panic is particularly unfortunate since sentry pretty often is involved in panics...

**Comment by Swatinem** [comment]
Like @jan-auer said, creating new hubs / pushing/popping scopes relies heavily on `im`, and it would seem that that library has been abandoned.
Which is unfortunate. We can just kick it our and use `Arc` and `make_mut` everywhere, at the cost of more allocations probably, so it is doable.

**Comment by dbrgn** [comment]
Thanks @Swatinem!
