### ISSUE TITLE
Replace failure dependency

### ISSUE THREAD

**Issue by dbrgn** [getsentry/sentry-rust#269]
As reported by `cargo-audit`, the `failure` dependency is officially unmaintained and should probably be replaced at some point in time.

```
Crate:  failure
Title:  failure is officially deprecated/unmaintained
Date:   2020-05-02
URL:    https://rustsec.org/advisories/RUSTSEC-2020-0036
Dependency tree:
failure 0.1.8
└── sentry-failure 0.20.1
    └── sentry 0.20.1
```

For libraries, I've made good experiences with [thiserror](https://docs.rs/thiserror/) in the past. For a "catch-all" error type, [anyhow](https://docs.rs/anyhow/) could be used (but it's probably not appropriate for a library).

**Comment by jan-auer** [comment]
The Rust SDK has an optional integration for `failure` for users still depending on this, but does not need it internally. We have actively deprecated it in https://github.com/getsentry/sentry-rust/pull/264 and will be removing it the release after.

Note that even in older versions of the SDK, the integration and thus also the dependency can be disabled via the `failure` feature flag. In the next upcoming release, it will be disabled by default.

**Comment by dbrgn** [comment]
Ah, I somehow missed that this was only an option. Sorry, and thank you for clarification!
