### ISSUE TITLE
sentry 0.20.x client doesn't log events

### ISSUE THREAD

**Issue by pjenvey** [getsentry/sentry-rust#277]
With the alternative CurlHttpTransport, 0.20.x of the client doesn't log events. Reverting back to 0.19 solves the issue.

I'm unable to easily try the default transport in this app (likely due to it linking boringssl which clashes w/ openssl, causing seg faults). With no other reports of 0.20.x failing in this way, I suspect it may only be an issue w/ the non standard transport.

**Comment by pjenvey** [comment]
debug output for 0.19 (successful):
```
[sentry] curl: > POST /api/.../store/ HTTP/1.1
Host: ...
Accept: */*
X-Sentry-Auth: Sentry sentry_key=..., sentry_version=7, sentry_timestamp=..., sentry_client=sentry.rust/0.19.1
Content-Type: application/json
Content-Length: 39285
[sentry] curl: {"event_id":"...",...}
[sentry] curl: < HTTP/1.1 200 OK
[sentry] curl: < Server: nginx
[sentry] curl: < Date: Fri, 06 Nov 2020 23:43:45 GMT
[sentry] curl: < Content-Type: application/json
[sentry] curl: < Content-Length: 41
[sentry] curl: < Vary: Accept-Encoding
[sentry] curl: < X-XSS-Protection: 1; mode=block
[sentry] curl: < X-Content-Type-Options: nosniff
[sentry] curl: < Content-Language: en
[sentry] curl: < Expires: Fri, 06 Nov 2020 23:43:45 GMT
[sentry] curl: < Vary: Accept-Language, Cookie
[sentry] curl: < Last-Modified: Fri, 06 Nov 2020 23:43:45 GMT
[sentry] curl: < Cache-Control: max-age=0
[sentry] curl: < X-Frame-Options: deny
[sentry] curl: < Strict-Transport-Security: max-age=31536000
[sentry] curl: < Via: 1.1 google
[sentry] curl: < Alt-Svc: clear
[sentry] curl: < 
```

debug output for 0.20's (failure):
```
[sentry] curl: > POST /api/.../envelope/ HTTP/1.1
Host: ...
Accept: */*
X-Sentry-Auth: Sentry sentry_key=..., sentry_version=7, sentry_timestamp=..., sentry_client=sentry.rust/0.20.1
Content-Type: application/json
Content-Length: 39372
[sentry] curl: {"event_id":"..."}
{"type":"event","length":39287}
{...}
[sentry] curl: < HTTP/1.1 403 OK
[sentry] curl: < Server: nginx
[sentry] curl: < Date: Fri, 06 Nov 2020 23:39:05 GMT
[sentry] curl: < Content-Type: text/html; charset=utf-8
[sentry] curl: < Content-Length: 6326
[sentry] curl: < Vary: Accept-Encoding
[sentry] curl: < X-XSS-Protection: 1; mode=block
[sentry] curl: < Content-Language: en
[sentry] curl: < X-Content-Type-Options: nosniff
[sentry] curl: < Vary: Accept-Language, Cookie
[sentry] curl: < X-Frame-Options: deny
[sentry] curl: < Via: 1.1 google
[sentry] curl: < Alt-Svc: clear
[sentry] curl: < 
[sentry] Failed to send event
```

**Comment by Swatinem** [comment]
I think this is related to #239 potentially, although that uses the default transport. Comment https://github.com/getsentry/sentry-rust/issues/239#issuecomment-702985716 describes issues with openssl as well.

**Comment by terry90** [comment]
Same here, `0.19.1` works, `0.21.0` does not.

`0.21.0` debug output:
```DEBUG hyper::server                > threads = 32
 DEBUG hyper::proto::h1::io         > flushed 249 bytes 
 DEBUG hyper::proto::h1::io         > flushed 705 bytes 
 DEBUG hyper::proto::h1::io         > read 1369 bytes 
 DEBUG hyper::proto::h1::io         > parsed 17 headers 
 DEBUG hyper::proto::h1::conn       > incoming body is chunked encoding 
 DEBUG hyper::proto::h1::decode     > incoming chunked header: 0x13CE (5070 bytes) 
 DEBUG reqwest::async_impl::client  > response '403 Forbidden' for https://sentry.[redacted].com/api/6/envelope/
 DEBUG hyper::proto::h1::io         > read 1369 bytes 
 DEBUG hyper::proto::h1::io         > read 1369 bytes 
 DEBUG hyper::proto::h1::io         > read 1369 bytes 
 DEBUG hyper::proto::h1::io         > read 553 bytes 
 DEBUG hyper::proto::h1::io         > read 5 bytes 
 DEBUG hyper::proto::h1::conn       > incoming body completed 
 DEBUG hyper::client::pool          > pooling idle connection for ("https", sentry.[redacted].com) 
 DEBUG hyper::server                > Incoming stream
```

**Comment by pjenvey** [comment]
The cause of this appears to be targeting an older (< v20.6.0) Self-Hosted (onpremise) Sentry. From [sentry-java#1001](https://github.com/getsentry/sentry-java/issues/1001#issuecomment-712854444):

> read the notes about Note for Sentry On Premise users:
>>  This version uses the envelope endpoint. If you are using an on-premise installation it requires Sentry version >= v20.6.0 to work. If you are using sentry.io nothing will change and no action is needed.

rust-sentry switched to Envelopes in 0.20.0 ([0.19.1..0.20.0](https://github.com/getsentry/sentry-rust/compare/0.19.1...0.20.0)):

## 0.20.0

**Breaking Changes**:

- The `Transport` was changed to work on `Envelope`s instead of `Event`s. The `send_event` trait function was removed in favor of `send_envelope`.


So one needs to either upgrade their Self-Hosted sentry or pin themselves to 0.19  (cc @terry90 -- looks like you're using onpremise).

Leaving this open as I think the CHANGELOG or README should include an obvious warning like sentry-java's.

**Comment by xrl** [comment]
This is a big waste of dev time, we tried upgrading our sentry-rust and couldn't find any reason in the documentation for what version of self-hosted sentry was supported. We just had to try things over and over again until it worked.
