### ISSUE TITLE
A way for users to audit information being sent to Sentry, and save to file

### ISSUE THREAD

**Issue by kellpossible** [getsentry/sentry-rust#281]
It would be nice to have some way for users to audit information being sent to Sentry before it is sent via this API. 
Also, perhaps related would be to have some backend which logs everything to a file in a human readable format such as JSON, which the user can then audit. Then some kind of offline support could also be built for security conscious users.

**Comment by jan-auer** [comment]
There are two ways you can achieve this:

1. Register a [`beforeSend` hook](https://docs.rs/sentry/0.20.1/sentry/struct.ClientOptions.html#structfield.before_send), which receives the event payload before being sent to Sentry. 

2. Register a [custom `Transport`](https://docs.rs/sentry/0.20.1/sentry/struct.ClientOptions.html#structfield.transport), which receives all payloads and is responsible for sending them to Sentry. You can wrap either the [default transport factory](https://docs.rs/sentry/0.20.1/sentry/transports/struct.DefaultTransportFactory.html) or one of the [Transport implementations](https://docs.rs/sentry/0.20.1/sentry/internals/trait.Transport.html), and then log all payloads there.

I agree, offline support sounds useful especially for applications running on consumer devices. May I ask about the security aspect that you're mentioning in regards to offline support?

**Comment by kellpossible** [comment]
> There are two ways you can achieve this:

Thanks! I'll look into it, seems like the custom transport might be the way to go.

> I agree, offline support sounds useful especially for applications running on consumer devices. May I ask about the security aspect that you're mentioning in regards to offline support?

For users who are running the application in a completely offline environment because they are concerned about the security implications. Being able to receive reports from them in a file format, if they had problems, to help diagnose, would be useful.

**Comment by jan-auer** [comment]
Thank you, in this case definitely go with a custom transport, as this will allow you to dump all data to the file system that would usually go to Sentry. You can try to format it in plain text, too, although using JSON formatting will probably be more straight forward. 

I think this use case makes a lot of sense. It is a bit of an edge case for our user base at the moment. We're absolutely happy to accept a PR on this, or otherwise back to this at a later time.

**Comment by JRAndreassen** [comment]
Hi...
This is actually fairly common among my customer base...
A lot of them run "Air-Gapped" systems...
So, I would find this "Transport-mode" useful as well..
Also, if you can run both direct and log, they can see what's there and decide if they want to disable.
There may also be some audit trail issues that could be satified with a dual mode...

Thanks
  JR

**Comment by kamilogorek** [comment]
https://github.com/getsentry/sentry-rust/issues/381 and corresponding https://github.com/getsentry/sentry-cli/pull/1254 in sentry-cli has been implemented, so there is an easy way to store the envelope locally and send it whenever it's feasible.

I'll let myself close this issue then, but please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!
