### ISSUE TITLE
Crashdump Attachment Support

### ISSUE THREAD

**Issue by Jake-Shadle** [getsentry/sentry-rust#299]
This is a follow up issue to #297, as that PR was originally made so that we could send minidumps using `sentry-core`, but had to remove a method that was added in that PR as it was out of scope.

The method in question was `Client::assemble_event`

```rust
/// Assembles an [`Event`] and [`SessionUpdate`].
///
/// Adds the additional context provided in the specified [`Scope`]
/// just as when using [`capture_event`](crate::Client::capture_event), but **without** actually sending
/// the event to sentry.
pub fn assemble_event(
    &self,
    event: Event<'static>,
    scope: Option<&Scope>,
) -> (Option<Event<'static>>, Option<SessionUpdate<'static>>) {
```

How it is used in [our Breakpad "integration"](https://github.com/EmbarkStudios/sentry-contrib-rust/tree/impl)

```rust
let mut eve = None;
let mut sess_update = None;

// Now fill out the event and (maybe) get the session status so
// that we can serialize them to disk so that we can add them
// into the same envelope as the actual minidump
if let Some(crash_hub) = crash_hub.upgrade() {
    // We **don't** do this because otherwise we lose the session
    // so intead, grab the session and just update it ourselves
    // crash_hub.end_session_with_status(protocol::SessionStatus::Crashed);
    if let Some(client) = crash_hub.client() {
        crash_hub.configure_scope(|scope| {
            let assembled = client.assemble_event(event, Some(scope));
            eve = assembled.0;
            sess_update = assembled.1;
        });
    }
}
```

The reason I am doing this is because of one of the [Attachment constraints](https://develop.sentry.dev/sdk/envelopes/#attachment) that is stated in the documentation, namely,

> For minidump and apple crash report attachments, the corresponding "event" Item must be sent within the same Envelope.

For now I'll just continue maintaining our fork of `sentry-core` since it's not onerous (at least so far)j so that we can integrate crashdump reporting with sentry-rust, but it would be nice to have some kind of path forward for Breakpad/Crashdump reporting from Rust that **doesn't** use `sentry-native` and the (unmaintained?) [`sentry-contrib-native`](https://github.com/daxpedda/sentry-contrib-native).

**Comment by repi** [comment]
Any updates to this from the Sentry team? We've been using this fork for 6 months now but really would like to get off it or hear something about it

**Comment by Swatinem** [comment]
Sorry for the delay. I still don’t think exposing such a function would be a good idea.
However I think such functionality should be possible to do with a custom transport maybe. Or having attachments on the scope, and then capturing events as usual?

**Comment by Jake-Shadle** [comment]
I've refactored it so that we just a use a custom `Transport` and massage event data during capture so that we don't need any modifications to sentry itself.
