### ISSUE TITLE
Reqwest error

### ISSUE THREAD

**Issue by zloypacifist** [getsentry/sentry-rust#318]
### Environment

Sentry SaaS (sentry.io) and self-hosted/on-premise

Which SDK and version?
rust 1.46

### Steps to Reproduce

1. I am using rust-sentry and grpcio 0.71 (or 0.60)
2.  When I run my code, errors occured in sentry-transport
### Expected Result

sentry-transport normally started

### Actual Result

thread 'sentry-transport' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Normal(ErrorStack([])) }' .cargo/registry/src/github.com-1ecc6299db9ec823/sentry-0.22.0/src/transport.rs:204:37

**Comment by Swatinem** [comment]
https://github.com/getsentry/sentry-rust/blob/3bf18cec754cef067837922d790af3e9159ad551/sentry/src/transport.rs#L196-L205

Do you have any proxy configured? Otherwise this is just the default reqwest builder, I don’t know why that would error when created.

**Comment by Swatinem** [comment]
@zloypacifist can you try again with `0.23.0`? The transport code was refactored a bit, though I still have no idea why reqwest would suddenly error in such a manner. Please re-open if this is still an issue.
