### ISSUE TITLE
Test execution hangs if guards are used in multiple tests

### ISSUE THREAD

**Issue by rasviitanen** [getsentry/sentry-rust#322]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
sentry-rust (0.22.0)

Toolchain:
stable-x86_64-pc-windows-msvc (default)
rustc 1.50.0 (cb75ad5db 2021-02-10)

### Steps to Reproduce
1. Define two tests that creates guards: 
```rust
#[test]
fn test_a() {
    let _guard = sentry::init(sentry::ClientOptions {
        ..Default::default()
    });
}

#[test]
fn test_b() {
    let _guard = sentry::init(sentry::ClientOptions {
        ..Default::default()
    });
}
```
2. Run `cargo test`
3. Get output:
```text
running 2 tests
test tests::test_a ... ok
test tests::test_b ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s 
```
4. Test execution freezes and doesn't return
5. Here is an example application to reproduce the problem: https://github.com/rasviitanen/sentry-bug

Running the tests individually works fine

### Expected Result

The test execution should finish with exit 0.

### Actual Result

```
running 2 tests
test observability::tests::test_a ... ok
test observability::tests::test_b ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 63 filtered out; finished in 0.03s 
<here it just freezes and you have to press ctrl+c to exit>
```

We didn't experience any issues with this in `0.19.0`

**Comment by rasviitanen** [comment]
I think I have tracked down the issue to these lines:
https://github.com/getsentry/sentry-rust/blob/f86a4db19d52d96b7d8c011f9c98dc502e1fff60/sentry-core/src/hub.rs#L158-L164

I guess it's the handeling of the PROCESS_HUB that doesn't work correctly when initializing sentry on multiple threads.

**Comment by Swatinem** [comment]
I think I have tracked this down to the `Drop` impl of our `SessionFlusher` which was implemented in #279.
It seems that the `PROCESS_HUB` holds on to a reference to the `Client` and thus to the `SessionFlusher`, which will never be dropped.

**Comment by Swatinem** [comment]
Oh, I see you were also on Windows, and interestingly enough I was also tracking this down on Windows.

This seems to have been a manifestation of https://github.com/rust-lang/rust/issues/74875 I guess since that matches the conclusion I came to in #326

**Comment by rasviitanen** [comment]
@Swatinem Amazing work, thank you!
