### ISSUE TITLE
sentry_actix 0.22 does not compile with actix-web 4.0.0-beta.6

### ISSUE THREAD

**Issue by a1ph** [getsentry/sentry-rust#327]
The problem is that tokio 1.x (which most people use these days) requires actix-rt 2.x, which requires actix-web 4.x, which does not seem to compile with sentry_actix (actix-web 3.x works fine). Any workaround? Thanks

```rust
267 |                 .wrap(sentry_actix::Sentry::new())
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Transform<actix_web::app_service::AppRouting, ServiceRequest>` is not implemented for `Sentry`
```

**Comment by Swatinem** [comment]
A WIP PR is open here: #316 however I don’t really want to merge that quite yet until actix-web 4 is final.

**Comment by jplatte** [comment]
Here's an updated patch for 4.0-beta.5 compatibility: https://github.com/lumeohq/sentry-rust/commit/462511cf03882713d19f9a37891b581bf4c16851

It's reporting all issues with an empty exception type and not much other useful data though, is that normal? (in particular I would expect the HTTP response code, which I don't get)
