### ISSUE TITLE
Nothing is working with example from docs

### ISSUE THREAD

**Issue by pashinin** [getsentry/sentry-rust#336]
### Environment

Self-hosted Sentry. Sample event works just fine.

Rust 1.52.1, sentry 0.22

Debian 10 with libssl1.1 ca-certificates pkgs

### Steps to Reproduce

```
use std::env;

fn main() {
    let guard = sentry::init(("https://...@.../2", sentry::ClientOptions {
        release: sentry::release_name!(),
        debug: true,
        ..Default::default()
    }));
    env::set_var("RUST_BACKTRACE", "1");

    if guard.is_enabled() {
        dbg!("Sentry is enabled");
    }

    sentry::capture_message("Hello World!", sentry::Level::Info);
    panic!("Everything is on fire!");
}
```

### Expected Result

Something will appear in Sentry.

### Actual Result

**Nothing** happens.

```
[sentry] enabled sentry client for DSN https://...:@.../2
[src/main.rs:13] "Sentry is enabled" = "Sentry is enabled"
thread 'main' panicked at 'Everything is on fire!', src/main.rs:17:5
stack backtrace:
   0: std::panicking::begin_panic
   1: test2::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[sentry] dropping client guard -> disposing client
[sentry] client close; request transport to shut down
[sentry] shutting down http transport
[sentry] dropping http transport
```

**Comment by flub** [comment]
Hi, using the latest `rust:latest` docker image which is also debian 10 rustc 1.52.1 I can not reproduce problem.  I copy pasted your example directly, only changing the DSN to point to a sentry.io-hosted location and the events arrive:

![image](https://user-images.githubusercontent.com/146720/119824504-442d8c00-bef6-11eb-95d8-35bfb9d3e1b8.png)

I suggest you try and narrow down which part of your infrastructure is breaking this flow.  Maybe you could start by sending to a test organisation on sentry.io as well to make sure client side things work before moving it back to your self-hosted installation?  In any case, as reported I don't think this is an issue with `sentry-rust`.  You can also use the resources at https://develop.sentry.dev/self-hosted/ and https://develop.sentry.dev/self-hosted/support/ for help with debugging your self-hosted installation, those channels have people who actually know about self-hosted :)

**Comment by pashinin** [comment]
Ok, thanks, will close it. Probably it's on my side then.
