### ISSUE TITLE
Different filter level for log integration and Sentry?

### ISSUE THREAD

**Issue by davechallis** [getsentry/sentry-rust#34]
Not 100% sure if this is a bug or whether my configuration is incorrect in this case.

I'm trying to set up Sentry with the log integration (and the `env_logger` crate), with `warn` and above sent to Sentry, and `debug` and above logged using `env_logger`.

I'm using something like the following:

```
#[macro_use] extern crate log;
extern crate env_logger;
extern crate sentry;  // version 0.3.1

fn main() {
    let _sentry = sentry::init(());

    let mut log_builder = env_logger::Builder::from_default_env();
    let logger_options = sentry::integrations::log::LoggerOptions {
        filter: log::LevelFilter::Warn, ..Default::default()
    };
    sentry::integrations::log::init(Some(Box::new(log_builder.build())), logger_options);

    debug!("debug message");
    info!("info message");
    warn!("warning message");
    error!("error message");
}
```
Then executing with:

    $ RUST_LOG=debug SENTRY_DSN=XXX ./target/debug/myapp

This outputs:

 WARN 2018-04-19T11:01:38Z: myapp: warning message
ERROR 2018-04-19T11:01:38Z: myapp: error message

So it looks like the `filter` in the log options are being applied to both Sentry and the env_logger - from the [docs](https://docs.rs/sentry/0.3.1/sentry/integrations/log/struct.LoggerOptions.html) I thought that this should just apply to Sentry's logger, with the `global_filter` setting being used if I wanted it to apply to both, but my understanding might be wrong here.

**Comment by mitsuhiko** [comment]
Right now you need to set the global filter I think for this to work as otherwise we do not know what to return from `enabled()`.

**Comment by davechallis** [comment]
@mitsuhiko thanks, makes sense now, will experiment with this. New API/client is excellent by the way, planning to get it into production shortly.

**Comment by terry90** [comment]
@mitsuhiko, this is a bit confusing:

With what I've read in the documentation, I tried to use the log feature like this:
```rust
    let mut log_builder = pretty_env_logger::formatted_builder().unwrap();
    log_builder.parse("simple_proxy=debug,ox=debug");

    sentry::integrations::log::init(Some(Box::new(log_builder.build())), Default::default());
```
And I expected pretty_env_logger to show my [DEBUG] logs.

This snippet works:
```rust
    let mut log_builder = pretty_env_logger::formatted_builder().unwrap();
    log_builder.parse("simple_proxy=debug,ox=debug");

    let logger_options = sentry::integrations::log::LoggerOptions {
        filter: log::LevelFilter::Warn,
        global_filter: Some(log::LevelFilter::Debug),
        ..Default::default()
    };
    sentry::integrations::log::init(Some(Box::new(log_builder.build())), logger_options);
```
It's useless to provide `"simple_proxy=debug,ox=debug"` without the global filter, I think this is the same as `"simple_proxy=info,ox=info"` due to the default level (`info`).
Maybe we could update the documentation ?

Thanks for your work, the crate is great 👍

**Comment by mitsuhiko** [comment]
@terry90 both docs updated as well as a `env_logger` specific integration added since that seems to be a common issue.
