### ISSUE TITLE
Default title for Sentry events differs from integrations in other languages

### ISSUE THREAD

**Issue by davechallis** [getsentry/sentry-rust#35]
I've noticed that when sending events from Sentry's log integration (v0.3.1), the title of the event is set to the name of the Rust application, whereas with other Sentry languages (e.g. Java/Python), the title of the event is the error message (or Exception class) itself.

E.g. if I log a message that's sent to Sentry (via the log integration) from a Rust binary named `sentrynew`, then the issue in Rust looks like:

<img width="488" alt="screen shot 2018-04-19 at 12 26 19" src="https://user-images.githubusercontent.com/208316/38988938-ec631cb2-43cc-11e8-87fb-4152001855b8.png">

Whereas issues in Sentry sent from other languages contain the error message in the title (or the Exception class in Java's case).

E.g.

<img width="480" alt="screen shot 2018-04-19 at 12 29 07" src="https://user-images.githubusercontent.com/208316/38989020-4bcfe7de-43cd-11e8-8a00-11c1cb8d0db6.png">

**Comment by mitsuhiko** [comment]
This only happens if you record errors as log messages. There is not much we can do as no error information is available. Errors should instead be recorded with `capture_error` and others where we attempt to recover an error name from the type's debug output.
