### ISSUE TITLE
Package depends on `sentry`, with features: `env_logger` but `sentry` does not have these features.

### ISSUE THREAD

**Issue by gonzalog** [getsentry/sentry-rust#352]
### Environment

Which SDK and version?
sentry-rust 0.23.0

### Steps to Reproduce

1. Add this line to Cargo.toml
```
sentry = {version = "0.23.0", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls", "env_logger"]}
```
2. Run `cargo build`

### Expected Result

Build with env_logger support

### Actual Result

Prints error:
```
Package depends on `sentry`, with features: `env_logger` but `sentry` does not have these features.
```

**Comment by Swatinem** [comment]
The `log` integration was re-architected some time ago already, removing this feature flag. The log integration is now independant of `env_logger`.
You have to initialize it yourself, as shown in these examples: https://docs.rs/sentry/0.23.0/sentry/integrations/log/index.html
