### ISSUE TITLE
sentry-slog: support for `emit_error`

### ISSUE THREAD

**Issue by jfirebaugh** [getsentry/sentry-rust#353]
slog added `emit_error` to `Serializer`, so that `std::error::Error`s can be serialized preserving their `source`: https://github.com/slog-rs/slog/pull/274

It would be great to add an `emit_error` implementation to sentry-slog's `MapSerializer` to preserve structured information about the error.

**Comment by szokeasaurusrex** [comment]
Hi, we would be happy to accept PRs for this feature, but given low demand for this feature and the team's limited capacity, it is unfortunately unlikely that we will be able to add this feature anytime in the near future. So, we will close this issue for now.
