### ISSUE TITLE
Automatically inherit scopes

### ISSUE THREAD

**Issue by Diggsey** [getsentry/sentry-rust#36]
Currently you have to explicitly bind scopes into new threads. This makes a sentry integration quite intrusive: I'd prefer to be able to bind once at the start of the program and have new threads inherit their scope automatically.

**Comment by mitsuhiko** [comment]
@Diggsey unfortunately rust has no api that can be hooked. Whatever is configured in the main thread will be implicitly configured for other threads now though.
