### ISSUE TITLE
User no longer appears in crash reports

### ISSUE THREAD

**Issue by alokedesai** [getsentry/sentry-rust#365]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Rust 0.23.0

### Steps to Reproduce
1.  Configure Sentry with a user
```rust
pub fn set_user(user: &User) {
    // Set user for Rust sentry.
    sentry::configure_scope(|scope| {
        let mut other = BTreeMap::new();
        if user.display_name.is_some() {
            other.insert(
                "Display Name".to_owned(),
                Value::String(user.display_name.as_ref().unwrap().clone()),
            );
        }
        scope.set_user(Some(sentry::User {
            email: Some(user.email.clone()),
            id: Some(user.local_id.clone()),
            ip_address: None,
            username: Some(user.screen_name.clone()),
            other,
        }));
    });
}
```
2. Crash the app
```rust
panic!("foo")
```

### Expected Result

The crash report should show the user

### Actual Result

The crash report does not show the user. 
![Image 2021-10-01 at 3 44 27 PM](https://user-images.githubusercontent.com/4110292/135677853-1e759cd5-11b2-4ac8-b9c6-35c7b1a4e81e.jpg)

This seems like a recent regression as none of our code has changed here and prior crash reports did report the user correctly. Any idea what could be causing this?

**Comment by Swatinem** [comment]
I have looked through the code, and there is no indication that the user is not being correctly passed on. Can you give a minimal code example to reproduce?

**Comment by FredrikNoren** [comment]
@Swatinem I'm having the same issue. I'm setting the user like this:

```rust
let user = Some(sentry::User {
    id: Some(id.into()),
    username: Some(display_name.into()),
    ..Default::default()
});
sentry::configure_scope(|scope| {
    scope.set_user(user.clone());
});
```

**Comment by FredrikNoren** [comment]
Hm this might be an OSX only issue; I see a user logged in a Windows bug report (but none in my 20+ OSX bugs).

**Comment by FredrikNoren** [comment]
Or maybe not.. I've seen user in OSX reports now as well, but it's really sporadic. Most of the time there's no user information.

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
