### ISSUE TITLE
Safe and production-ready to use in Android?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-rust#367]
Hi thanks for the lib! I wonder whether this lib is safe and production-ready to use in Android? More specifically:

1. Will it crash (segfault, etc) once in a while? Because I see [backtrace](https://docs.rs/backtrace/0.3.61/backtrace/) says that `... can lead this library to segfault ...`.
2. Will the symbols be symbolized? Since https://github.com/rust-lang/rust/issues/17520 seems to be an open issue.
3. Most importantly, are we ensured that the problems above never happen **on every mobile phone** (Android>=21 is acceptable)? In other words, if most of the phones work, but a small portion of phones crash or segfault, that is still terrible.

I am willing to use Sentry Rust but I have the worries above. Thanks for any suggestions!

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
saas

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
rust latest

### Steps to Reproduce

n/a

### Expected Result

n/a

### Actual Result

n/a

**Comment by Swatinem** [comment]
> Is this Sentry-Rust used in Android and iOS environments before?

Not that I know of.

**Comment by rajivshah3** [comment]
We have an app that uses Rust and Electron (using Sentry SDKs for both), and are using the Rust component in our [Capacitor](https://capacitorjs.com/)-based mobile app that we're developing. We're looking at using the Sentry Rust SDK there as well. Once we work on adding Sentry to the mobile app I'm happy to leave comments here regarding any issues we run into (as well as contribute fixes if possible)

**Comment by fzyzcjy** [comment]
@rajivshah3 By the way, I have successfully bundled sentry into my app in production (android + ios) and it seems to work well. Not see big issues up to now

**Comment by audkar** [comment]
@fzyzcjy Do you have Sentry running on both sides (Kotlin & Rust)? Are spans, breadcrumbs, transactions shared between then?

**Comment by fzyzcjy** [comment]
@audkar I use Sentry for flutter + rust and is communicated vis https://github.com/fzyzcjy/flutter_rust_bridge. None is shared.

**Comment by Swatinem** [comment]
Sharing scope data between different language SDKs is always a challenge. So far, most of our Mobile focused SDKs that bundle sentry-native have implemented Scope-sync. Though nothing on the Rust side I know of.

**Comment by smeubank** [comment]
there is no known reason why this lib is not safe and prod ready for Android use. If a reason is found. Let's create a specific issue. Closing, feel free to reopen if my understanding is wrong!

**Comment by fzyzcjy** [comment]
Sure!
