### ISSUE TITLE
Safe and production-ready to use in iOS?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-rust#368]
This is counterpart of #367 , but since android and ios are often quite different in architecture, I create a separate issue.

---

Hi thanks for the lib! I wonder whether this lib is safe and production-ready to use in Android? More specifically:

1. Will it crash (segfault, etc) once in a while? Because I see [backtrace](https://docs.rs/backtrace/0.3.61/backtrace/) says that `... can lead this library to segfault ...`.
2. Will the symbols be symbolized? Since https://github.com/rust-lang/rust/issues/17520 seems to be an open issue.
3. Most importantly, are we ensured that the problems above never happen **on every mobile phone** (Android>=21 is acceptable)? In other words, if most of the phones work, but a small portion of phones crash or segfault, that is still terrible.

I am willing to use Sentry Rust but I have the worries above. Thanks for any suggestions!

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
saas

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
rust latest

**Comment by kamilogorek** [comment]
Closing the issue, as it seems like the original issue has been answered.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

**Comment by fzyzcjy** [comment]
Btw I have been using it for half a year without problems. 🎉

**Comment by kamilogorek** [comment]
@fzyzcjy great to hear that, thanks for letting us know!
