### ISSUE TITLE
Support sending a serialized envelope via Transport

### ISSUE THREAD

**Issue by kornelski** [getsentry/sentry-rust#381]
I need to report errors from a process that runs in an off-line sandbox, without its own access to a network. The process can serialize and pass on messages to be sent from another process (like Chrome Renderer helper and Chrome root process). Related to #281

Sentry supports pluggable `Transport` which can be used to capture an `Envelope`, and `Envelope` supports serialization via `to_writer`, so I can move it between processes easily. However, the `Transport` trait can't send a serialized `&[u8]` representation of the envelope, so I can't reuse Sentry's implementation of networked transports. I need to reinvent the whole transport logic myself, including retry-after and rate limiting logic, which I'd rather not duplicate. 

* Could you extend the `Transport` trait to support sending of an already-serialized envelope from `&[u8]` or `Vec<u8>` representation?

* Or, could you make it possible to parse `Envelope` object back from its serialized representation, so that I can feed it back to a `Transport`?

* Alternatively, could you make [`TransportThread`](https://github.com/getsentry/sentry-rust/blob/a77bdcefd7c3e976391587549e1a5818a192821b/sentry/src/transports/thread.rs) public, so I would only need to copy-paste only the easy parts of an http client implementation?

**Comment by Swatinem** [comment]
I think one way to solve this would be to create a "raw" `Envelope`, similar to what we have in `sentry-native`.

Also, I wanted to expose the retry-after and rate-limiting logic so that it can be reused by third parties. I think we will be doing that soon-ish.

**Comment by kamilogorek** [comment]
@Swatinem please ping me once it's decided and implemented, so I'll pull this down to `sentry-cli` as well :)

**Comment by smeubank** [comment]
@Swatinem any update on this? We added this to our sentry-cli roadmap #1168

**Comment by Swatinem** [comment]
We haven’t planned for this yet. However I don’t expect this to be a huge change.
