### ISSUE TITLE
Will segfault be caught and reported?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry-rust#389]
Hi thanks for the lib! I wonder whether segfault be caught and reported? IMHO it is usually caused by things like invalid memory access, and at the time this signal happens, the memory may already be corrupted. Thus, I wonder whether sentry can still capture this error and report it to sentry server so that I can see it?

**Comment by Swatinem** [comment]
The Rust SDK does not, but we have https://github.com/getsentry/sentry-native dedicated to native crashes, though it is written in C so it is more effort to integrate into a Rust project.
https://github.com/daxpedda/sentry-contrib-native/ was done by a third-party, as a convenient Rust wrapper around the native SDK, however that project seems to be largely abandoned by now.
