### ISSUE TITLE
Feature names, follow the guideline

### ISSUE THREAD

**Issue by Kerollmops** [getsentry/sentry-rust#40]
It will be a breaking change if you update features names but the guideline doesn't like the names you used 😄 

https://rust-lang-nursery.github.io/api-guidelines/naming.html#c-feature

**Comment by mitsuhiko** [comment]
Until namespaced features land we can't rename them as we share the same names as the dependencies we have.

**Comment by Kerollmops** [comment]
Ho ok, good point !

**Comment by mitsuhiko** [comment]
Going to close this. We won't change this going forward.
