### ISSUE TITLE
0.24?

### ISSUE THREAD

**Issue by jacobsvante** [getsentry/sentry-rust#413]
Over 6 months months since last release. What are your plans for 0.24?

**Comment by Swatinem** [comment]
We are putting the finishing touches on the release, it should go out soon ;-)

**Comment by jacobsvante** [comment]
Nice! Almost sounds like today?! 😃

**Comment by Swatinem** [comment]
Well, fun fact: we tried already a couple of times, but were held up by automation troubles and finding some last minute fixes we wanted to squeeze into the release.

**Comment by jacobsvante** [comment]
Gotta squeeze in all of the fixes!

Good luck with the release 👍

**Comment by Swatinem** [comment]
`0.24.1` is out now! 🎉

**Comment by jacobsvante** [comment]
Wihooo! GJ!
