### ISSUE TITLE
sentry-tracing: Errors show up under wrong names in sentry

### ISSUE THREAD

**Issue by loewenheim** [getsentry/sentry-rust#427]
### Environment

How do you use Sentry?
Sentry 4 Sentry

Which SDK and version?
`sentry-rust 0.24.2`

### Steps to Reproduce

With `sentry-tracing` enabled, call `tracing::error!`

### Expected Result

The error shows up in sentry under a sensible name

### Actual Result

The error shows up in Sentry with a name like `event crates/symbolicator/src/services/objects/data_cache.rs:189 download_file`.

This behavior has already been fixed in https://github.com/getsentry/sentry-rust/pull/423. We're keeping this open as a tracking issue until we know what behavior we actually want to see instead.

**Comment by szokeasaurusrex** [comment]
> This behavior has already been fixed in https://github.com/getsentry/sentry-rust/pull/423. We're keeping this open as a tracking issue until we know what behavior we actually want to see instead.

So this is done @loewenheim?

I guess I'll close this issue, please reopen if still relevant
