### ISSUE TITLE
Release new 0.19 version with updated dependencies 

### ISSUE THREAD

**Issue by glebpom** [getsentry/sentry-rust#431]
We met the problem with the latest version of the rust sentry client. Our on-premise Sentry server is outdated and doesn't support the `envelope` API. Panics didn't report, and it took some time to find out why. The last sentry client used the legacy API was `0.19.1`. However, its dependencies are outdated. Wouldn't it work to release a sentry version `0.19.2` with updates `reqwest`, `actix-web` and maybe something else, and point in the documentation that `0.19.x` is the desired version to work with legacy sentry server?

**Comment by loewenheim** [comment]
Sorry, we are not going to patch an old version.

**Comment by glebpom** [comment]
For those, who meet the same problem [see PR](https://github.com/getsentry/sentry-rust/pull/432)
