### ISSUE TITLE
sentry-tracing: dropping spans

### ISSUE THREAD

**Issue by jessfraz** [getsentry/sentry-rust#438]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Rust (master)

### Steps to Reproduce

So I have many functions that call functions that call functions, etc, etc, you get the drift. It does not seem that all the child spans are being traced, as in I have `#[tracing::instrument]` everywhere but it seems only 1st-level children are traced not children of children, its very odd.

### Expected Result

I excepted many recursive children to also work.

### Actual Result

Missing a lot of tracing data. It should also be noted that I'm tracing 100% so that's not why things are being dropped if that helps.

**Comment by jessfraz** [comment]
also i know this is an experimental feature but figured you'd appreciate testing

**Comment by Swatinem** [comment]
Can you give me a more detailed example?

In particular, the sentry implementation differs a bit from `tracing` as the span hierarchy is not copied from `tracing`, but rather based on which `Hub` is currently active when you create a new span.

Maybe you are experiencing an issue similar to the one I blogged about here: https://swatinem.de/blog/non-lazy-futures/

**Comment by jessfraz** [comment]
Ah interesting that is likely what is happening, I'll mess around with it!

**Comment by jessfraz** [comment]
i think i got this sorted, thanks!
