### ISSUE TITLE
tracing: added fields don't show up in Sentry

### ISSUE THREAD

**Issue by jessfraz** [getsentry/sentry-rust#440]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Rust, master

### Steps to Reproduce

Adding custom fields in the `tracing::instrument` don't show up anywhere in sentry.

example:
```
#[tracing::instrument(
        fields(
            db.name=%self.info.current_database,
            db.system="postgresql",
            db.version=%self.info.version,
            db.user=%self.info.user,
            db.statement=%query,
            otel.kind="client",
        ),
        skip(self),
    )]
```

### Expected Result

I kind thought those would be tags or data, judging by the code it looks like data but either way works.

### Actual Result

The data does not show up in sentry at all

**Comment by jessfraz** [comment]
I think I can fix this, it works when you call `span.record` but just not on the initial new span

**Comment by jessfraz** [comment]
hmm I don't see those on mine? I also realized that I don't see arguments passed into the function as well (the ones that aren't skipped) and I assume those would show up in the same place?

**Comment by jessfraz** [comment]
for example this is what I see, and I know there is an arg passed into this function that is a string, and I assume it would show up here
<img width="880" alt="Screen Shot 2022-03-02 at 4 44 48 PM" src="https://user-images.githubusercontent.com/1445228/156474329-3b6e4496-9825-432c-aca0-cfab142f1d8c.png">

or maybe this is not the spot you are talking about?

**Comment by jessfraz** [comment]
oh this is an async function I am `await`ing on maybe its that, since it says status unknown?

**Comment by jessfraz** [comment]
Also fwiw I think its fair to not use tags because a lot of it is like gobbleygook

**Comment by flub** [comment]
Apologies for the delay in getting back.

> or maybe this is not the spot you are talking about?

That is the right place to look, it should show up as a section like "SDK" and "TRACE DETAILS" do.  But evidently it does not.

Since you talk about maybe not awaiting futures and span.record, any chance you could create something minimally reproducible?  It's a bit hard to think of how to figure this out in the abstract.

**Comment by DmitrySamoylov** [comment]
A reproducible example is [here](https://github.com/DmitrySamoylov/test-sentry-spans).

```rust
#[instrument]
fn make_an_error(span_field: &str) {                   // span_field IS NOT sent to sentry
    error!(event_field = "event_field_value", "test"); // event_field IS sent to sentry
}
```

I expect both `span_field` and `event_field` appear somewhere at event page, but I only see `event_field`:

![image](https://user-images.githubusercontent.com/56959852/159029301-d9b2a783-5cfd-4ac3-b2d6-56ec16da7a3c.png)

I'd be fine with manual mapping (in `event_mapper`) of fields to sentry tags or to non-searchable data ("Rust Tracing Tags"). But is there some way to get span fields in `event_mapper` callback?

**Comment by DmitrySamoylov** [comment]
> Adding custom fields in the `tracing::instrument` don't show up anywhere in sentry.

It seems, those still don't show up in new version `0.26.0` ([example](https://github.com/DmitrySamoylov/test-sentry-spans/blob/62e2e94a3fb697ec5cb410200dcbed5f6b115d30/src/main.rs#L27-L32)).
