### ISSUE TITLE
slow http/db ops UI question

### ISSUE THREAD

**Issue by jessfraz** [getsentry/sentry-rust#446]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Sentry-rust master 

So I have all these `http.server` `db.sql.query` etc spans/transactions but they don't show up in the UI under slow http/db ops

See below
<img width="1424" alt="Screen Shot 2022-03-15 at 9 10 00 AM" src="https://user-images.githubusercontent.com/1445228/158422224-607bce2b-f586-4d27-9cbd-d49551bfca6a.png">

I tried looking at the source code for the js client and it seems like I'm doing all the same stuff. I tried looking at the UI code and it seems like it should work for `http` and `db` ops so I guess I'm wondering do I need to explicitly call it that versus `http.server` or an I missing some other param?

Any help is appreciated

**Comment by jessfraz** [comment]
My secondary question is do you all have a discord or IRC channel you hang out in because I have a few other questions but don't want to spam your issues

**Comment by jessfraz** [comment]
the difference actually seems to be a breadcrumb with category `http` or `db` in each, so is that necessary?

**Comment by Swatinem** [comment]
> do you all have a discord or IRC channel you hang out in

Our discord server is linked from the Readme. You can find me and the rest of the team in the `rust` channel and a few others.

As for the actual question, I will forward this to someone else who might be able to help you with that.

**Comment by syphar** [comment]
@Swatinem I was digging into sentry performance for docs.rs itself, and was missing the sql queries too. 

Is it perhaps enough to set an specially crafted tracing-span that could be picked up by the sentry SDK? 

or is this special behaviour in the SDK that I would have to call separately?

**Comment by Swatinem** [comment]
> Is it perhaps enough to set an specially crafted tracing-span that could be picked up by the sentry SDK?

Yes, pretty much you would need `op: db` and `description: RAW SQL`. that is what other SDKs with auto-instrumentation are doing.

Some problems might be:
- The `#[tracing::instrument]` integration automatically infers the `op` and `description` from the tracing span name.
- Not relevant for the Rust SDK in its current form, but there was talk about deprecating the difference between op/description at some point, though I don’t yet know how that would change this auto-classification.

**Comment by smeubank** [comment]
In the most up to date versions of Sentry we have moved to a focus on [DB/Query Insights](https://docs.sentry.io/product/insights/backend/queries/), where we have also done a better job of [documenting the minimum requirements](https://develop.sentry.dev/sdk/telemetry/traces/modules/queries/) to populate data in the queries insights modules.

I will close this issue since it is based on an old view of the Sentry performance product. If my understanding is wrong please feel free to re-open!

**Comment by amadeusCaleb** [comment]
For anyone looking how to do this you can do something similar to 

```rust
tracing::span!(
    Level::INFO,
    "db.query",
    message = sql,
    "db.system" = "postgresql"
)
```
