### ISSUE TITLE
Report macOS versions instead of Darwin kernel versions

### ISSUE THREAD

**Issue by rajivshah3** [getsentry/sentry-rust#449]
In other Sentry SDKs, the version of macOS is either found directly by using Objective-C APIs (ex: [sentry-cocoa](https://github.com/getsentry/sentry-cocoa/blob/cd561c7b8f5e0396f3510600167c17b2c076deed/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_System.m#L510)) or using  the `sw_vers` command and falling back to a heuristic (ex: [sentry-electron](https://github.com/getsentry/sentry-electron/blob/11a6d8c64e5f26a5b95bc3144459f85ea8f38336/src/main/context.ts#L105)) to figure out the macOS version from the Darwin kernel version. Currently, errors coming from the Sentry Rust SDK [report the Darwin kernel version](https://github.com/getsentry/sentry-rust/blob/9dcbeebdf08e4eaa3f6007a3830a07834478d3cd/sentry-contexts/src/utils.rs#L90) instead of the macOS version. It would be great if the macOS version is reported, in line with the other SDKs. 

I think the best approach would be to do `sw_vers` and fall back to the heuristic, like the Electron SDK does, but this wouldn't work on iOS (maybe there's a heuristic for that too?). I'm happy to work on this change but I wanted to get some feedback before beginning.

**Comment by Swatinem** [comment]
> I'm happy to work on this change but I wanted to get some feedback before beginning.

Doing this is a very good idea!

The `sentry-contexts` integration already uses `libc::sysctlbyname`:

https://github.com/getsentry/sentry-rust/blob/9dcbeebdf08e4eaa3f6007a3830a07834478d3cd/sentry-contexts/src/utils.rs#L13

The API is called twice, first to query the needed buffer size, and then to actually write the result. I think you can abstract that out into its own method.

You should be able to query the `kern.osproductversion` key, as `sentry-native` does:

https://github.com/getsentry/sentry-native/blob/9eecb1bdf2c7762ba7babe9ea437545a1f759bdc/src/sentry_os.c#L130

This should give you enough pointers to get started. Looking forward to your contribution! ❤️

**Comment by rajivshah3** [comment]
> You should be able to query the `kern.osproductversion key`, as `sentry-native` does:

Ah nice! Thanks for the link, I thought I had seen a way to do it with `sysctlbyname` before but I couldn't remember where I found it. I like that a lot better than doing `sw_vers` or using a heuristic, and it might work for iOS as well
