### ISSUE TITLE
Support for EdgeDB

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-rust#458]
Build an integration for Edge DB.
Having built in support for tracing with EdgeDB.

https://www.edgedb.com/

This is the official rust client:
https://github.com/edgedb/edgedb-rust

If you want to have such an integration, please "thumb up" this issue, to measure the the demand.

**Comment by szokeasaurusrex** [comment]
Given low demand for this feature and a lack of capacity on the team to build and maintain this new feature, we are closing this issue for now. We would gladly accept PRs if anyone would like to contribute one.
