### ISSUE TITLE
Release 0.26 or 0.25.1 with updated uuid 1.0

### ISSUE THREAD

**Issue by poliorcetics** [getsentry/sentry-rust#459]

**Comment by jhpratt** [comment]
@mitsuhiko @Swatinem Any chance this could happen? :slightly_smiling_face: This is one of the last things that needs to happen for my company to upgrade to uuid 1.0.

**Comment by Swatinem** [comment]
We just released `0.26.0`. Sorry for the long delay here.

**Comment by jhpratt** [comment]
Thanks!
