### ISSUE TITLE
sentry only shows error!() msgs, not lower

### ISSUE THREAD

**Issue by Boscop** [getsentry/sentry-rust#46]
Any idea why sentry only shows my `error!()` msgs in the dashboard, not `warn!()` or `info!()`? 
Even though I configured it with level `Info`:
```rust
#[macro_use] extern crate log;
extern crate env_logger;
#[macro_use] extern crate sentry;

use sentry::integrations::panic::register_panic_handler;

fn main() {
	let _guard = sentry::init(("...", sentry::ClientOptions {
		release: sentry_crate_release!(),
		..Default::default()
	}));
	register_panic_handler();
	let mut log_builder = env_logger::Builder::new();
	log_builder.parse("info");
	let logger_options = sentry::integrations::log::LoggerOptions {
		filter: log::LevelFilter::Info, ..Default::default()
	};
	sentry::integrations::log::init(Some(Box::new(log_builder.build())), logger_options);
	warn!("test run warn");
}
```
Btw, do I have to use the same log level for the logger **and** sentry?

**Comment by mitsuhiko** [comment]
That's because no global log level was set. We added the `env_logger` integration in the last release which makes this harder to misconfigure: https://docs.rs/sentry/0.5.4/sentry/integrations/env_logger/index.html

(See also #34 for some discussion around this issue)

**Comment by Boscop** [comment]
Hm, this also doesn't seem to work:
```rust
#[macro_use] extern crate log;
extern crate env_logger;
#[macro_use] extern crate sentry;

use sentry::integrations::panic::register_panic_handler;

fn main() {
	let _guard = sentry::init(("...", sentry::ClientOptions {
		release: sentry_crate_release!(),
		..Default::default()
	}));
	register_panic_handler();
	let mut log_builder = env_logger::Builder::new();
	log_builder.parse("info");
	let logger_options = sentry::integrations::log::LoggerOptions {
		filter: log::LevelFilter::Info,
		global_filter: Some(log::LevelFilter::Info),
		..Default::default()
	};
	sentry::integrations::env_logger::init(Some(log_builder.build()), logger_options);
	warn!("test run warn");
}
```
It still only shows it in my dashboard when I change the call to `error!()`..

**Comment by Boscop** [comment]
Ah, makes sense. Are all logging levels used as breadcrumbs?

Btw, what exactly constitutes a User? 
If there are multiple clients and 1 server, should everyone of them be a User with a different api key to distinguish which one reported an error?

**Comment by mitsuhiko** [comment]
All logging levels above `filter` are used for breadcrumbs. Info by default.

User is whatever you want to set. Typically it's someone who interacts with the app (authorized user for instance). Can be set as such:

```rust
sentry::configure_scope(|scope| {
    scope.set_user(sentry::User {
        username: Some("something".into()),
        ..Default::default()
    });
});
```

**Comment by Boscop** [comment]
Ah, thanks :) 
By above, do you mean `>` or `>=`?

So when not setting a User per client, it won't be possible to see which client reported an error?

**Comment by mitsuhiko** [comment]
Basically, yes.
