### ISSUE TITLE
Backtrace wrong when using tokio (windows)

### ISSUE THREAD

**Issue by FredrikNoren** [getsentry/sentry-rust#470]
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
0.26.0

### Steps to Reproduce

I'm capturing a panicking unwrap with sentry, but for some reason it doesn't show any of my own code in the backtrace (just tokio and some system code). I'm also using sentry-contrib-breakpad 0.4, not sure if that affects things. Also not sure if tokio is part of the problem here.

### Expected Result

I would expect it to show me where in my own code the unwrap happened. 

### Actual Result

Here's a screenshot. None of the backtrace rows are in my code.
 
<img width="1206" alt="Screenshot 2022-05-30 at 18 36 49" src="https://user-images.githubusercontent.com/1288009/171033194-2630828a-6c76-4938-8670-af39c8615979.png">

**Comment by FredrikNoren** [comment]
@Swatinem Sorry for an even later answer, but I got something like this again. Here's a link to an error: https://sentry.io/share/issue/2df7c06320aa4e43ab221800c8973861/

**Comment by FredrikNoren** [comment]
@Swatinem Oh that sounds amazing, I'll try upgrading to a newer nightly version.

Hm no I don't think it's an unwrap at the root.

**Comment by Swatinem** [comment]
This might have to do with not resolving inlined functions when symbolicating.

The actual async fn body was likely inlined into the outer `GenFuture` wrapper, and thus not visible in the stack trace in case inline functions were not resolved.

If you enable the `debug-images` feature (we will make this the default with the next release as well) and upload debug files to sentry, it should resolve inlined functions correctly.

Also, my work to remove `GenFuture` completely has landed in Rust 1.67, so there are other improvements there as well.

Please reopen if this is still a problem.

**Comment by gautamg795** [comment]
I'm encountering this as well once upgrading to sentry-rust 0.30.0 (i.e. once `debug-images` was enabled by default)
We previously ran release-mode binaries with debuginfo built in, so there was no need to upload symbols to Sentry — however with `debug-images` enabled, Sentry notes errors processing the events until I use the CLI to upload the binary though still has correct stack traces.
Once I do upload the binary to correct this issue, the stack traces become useless and are all tokio-related frames.
e.g. stack trace with `debug-images` enabled, no binary uploaded to sentry:
![image](https://user-images.githubusercontent.com/3837919/225159454-a6d2b1df-7b9b-49f0-8bee-78436aeeda66.png)
stack trace with `debug-images` enabled,  binary uploaded to sentry:
![image](https://user-images.githubusercontent.com/3837919/225159532-c11325f8-30c6-42d5-ab31-bdd50b240242.png)
bonus, same stack trace above but with "unsymbolicated" chosen as the display option:
![image](https://user-images.githubusercontent.com/3837919/225159587-441daf99-232e-478c-9a6a-6921306f35b9.png)


pretty odd that choosing "unsymbolicated" restores the frames we care about! as a short term fix I'll probably just disable `debug-images` again as our binaries already have debuginfo in them, but I'd love to be able to move back to server-side symbolication as our binaries grow larger

**Comment by Swatinem** [comment]
Hi @gautamg795 , thanks for the report.

This would seem like maybe some of the offsets reported by the debug-images integration could be wrong.

Can you provide a link to an event that has this problem?

**Comment by gautamg795** [comment]
Thanks for the quick response. This is on hosted Sentry for a private repo -- if you (as a Sentry employee) can access a private link I provide, happy to do so but I don't otherwise have a publicly shareable event I can link

**Comment by Swatinem** [comment]
Yes, as an employee I can look at the events as a matter of customer support :-)

If you do not want to share that publicly you can also mail it to me at arpad.borsos@sentry.io

**Comment by gautamg795** [comment]
Emailed you, thanks!

**Comment by gautamg795** [comment]
Thanks for the deep investigation! I haven't had a chance to try with a stripped build yet but it's on my list for next week and I'll get back to you with the results.

**Comment by gautamg795** [comment]
Just confirmed with a stripped build + uploaded symbols that backtraces work correctly / as expected — thanks for figuring this out.

It'll take some time for me to integrate symbol uploading into our build pipeline so I was going to just leave `debug-images` off for now and continue deploying builds with debuginfo — are there any downsides to continuing with this approach? 
i.e. other than allowing for smaller binaries in production, any reason we should be moving towards stripped binaries + `debug-images` + uploaded symbols?

**Comment by Swatinem** [comment]
The only additional selling point would be that you can also upload and display source context on sentry :-)

**Comment by julienfouilhe** [comment]
Wow, I've been trying to get stack traces working for a few weeks now, to think that the option I thought essential turned out to be the culprit.
I removed `debuginfo = true` from my `release` profile and I now have understandable stack traces. 🎉

Btw the issue title says "(windows)" but the same problem also exists on macOS and Linux.
