### ISSUE TITLE
Fields from `#[instrument]` don't show up at sentry.io event page

### ISSUE THREAD

**Issue by DmitrySamoylov** [getsentry/sentry-rust#480]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Rust 1.62, sentry-tracing = "0.27.0"

### Steps to Reproduce

[Example repo](https://github.com/DmitrySamoylov/test-sentry-spans/blob/62e2e94a3fb697ec5cb410200dcbed5f6b115d30/src/main.rs#L27-L32)

```rust
// "span_field" doesn't appear at sentry.io
// "event_field" appears at sentry.io
#[instrument]
fn make_an_error(span_field: &str) {
    error!(event_field = "event_field_value", "test");
}
```

### Expected Result

Both "event_field" and "span_field" appear somewhere at sentry.io

### Actual Result

"event_field" is there but "span_field" doesn't appear at event page.

![image](https://user-images.githubusercontent.com/56959852/176907633-0b8af1b6-6d5f-4211-ba9e-913533749f42.png)

**Comment by Swatinem** [comment]
The `#[instrument]` fields are attached to transactions/spans.
In your example you have two problems that prevent you from getting those:
* you are not sampling any transactions, as they are opt-in. You need to set `traces_sample_rate: 1.0` on your `ClientOptions`.
* your `EnvFilter` is filtering out the spans so they never reach the sentry layer.

With these two things taken care of, span data turns up *on the transaction* (you need to navigate there via your trace):

![grafik](https://user-images.githubusercontent.com/580492/177288188-e8c1a0cb-d324-467d-a64b-2e798f4d06a4.png)

![grafik](https://user-images.githubusercontent.com/580492/177287532-beb53453-41f1-4660-9c36-a9e2e11a50d5.png)
