### ISSUE TITLE
Capture backtrace from `tracing::error!`

### ISSUE THREAD

**Issue by peterstuart** [getsentry/sentry-rust#501]
Is it possible to capture backtraces from errors when using `sentry_tracing`?

```rust
tracing::error!(error = ?anyhow!("Test error"), "Error");
```

The example above (with the `backtrace` feature of `anyhow` enabled), does record the backtrace as a string in the "error" field of the event recorded by Sentry, but it doesn't seem to get picked up as a "real" backtrace. I see https://github.com/getsentry/sentry-rust/pull/412 and some related discussions which made it seem like this was supported and I'm doing something wrong, but I couldn't figure out how to make this work with the tracing integration.

Thanks!

**Comment by Swatinem** [comment]
In your example the `?` in `?anyhow!("Test error")` means that tracing with use the `Debug` representation, which as you mentioned has the stringified stack trace.

You can `as_ref()` the error to turn it into a `&dyn Error` which I think tracing will pick up. They have a similar thing in their own docs: https://docs.rs/tracing/latest/tracing/#for-log-users

However, a `std::error::Error` does not have a backtrace itself `yet`, and we do not try to upcast it to an `anyhow::Error` either.
The modularity of the SDK means that the tracing integration does not know about the anyhow integration.

I don’t think this is currently possible. But the Rust ecosystem is slowly moving, and eventually we will have a backtrace in the standard library. But that will take a long time still.

**Comment by peterstuart** [comment]
Ah, I see. Thanks for the explanation!
