### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by lpraneis** [getsentry/sentry-rust#503]
Just wondering about the plan for a new release since it has been a few months since 0.27.0.

**Comment by kamilogorek** [comment]
We will release next minor once https://github.com/getsentry/sentry-rust/pull/504 is merged :)

**Comment by lpraneis** [comment]
Is there any updated estimate for the release? Thanks!

**Comment by kamilogorek** [comment]
@lpraneis we're on it! Will do it today

**Comment by kamilogorek** [comment]
`0.28` is out. Cheers!
