### ISSUE TITLE
Couldn't attach a crash dump

### ISSUE THREAD

**Issue by italiks** [getsentry/sentry-rust#521]
### Environment
Window 10, x64

What version are you running? Etc.
sentry = 0.27
### Steps to Reproduce

I'm writing crash handler for unhandled exceptions and want to attach a crash dump but got an error ```[sentry] Get response: `{"detail":"invalid event envelope","causes":["invalid item header","invalid escape at line 1 column 53"]}```.
Here is a snippet code:
```
let crash_dump = write_minidump(context);

with_scope(
	|scope| {
		if let Ok(crash_dump_path) = crash_dump {
			scope.add_attachment(Attachment {
				ty: Some(AttachmentType::Minidump),
				buffer: std::fs::read(crash_dump_path.as_path()).unwrap(),
				filename: crash_dump_path.into_os_string().into_string().unwrap(),
				content_type: None,
			})
		}
	},
	|| {
		let event = Event {
			exception: vec![Exception {
				ty: "native unhandled exception".into(),
				mechanism: Some(Mechanism {
					ty: "native crash handler".into(),
					handled: Some(false),
					..Default::default()
				}),
				value: Some(format!(
					"Unhandled exception. Excepion code - {:#x}",
					context.exception_code
				)),
				stacktrace: make_stacktrace(context),
				..Default::default()
			}]
			.into(),
			level: Level::Fatal,
			..Default::default()
		};

		let confirm_uuid = sentry::capture_event(event);

		if confirm_uuid == Uuid::nil() {
			println!("failed to capture native event");
		}
	},
);
```

### Expected Result

Crash event will be sent with an attached dump

### Actual Result

Failed to sent with a message ```[sentry] Get response: `{"detail":"invalid event envelope","causes":["invalid item header","invalid escape at line 1 column 53"]}```.

**Comment by timfish** [comment]
I don't have my laptop on me so haven't tried your code but the error suggests there's something wrong in the header and  `crash_dump_path.into_os_string()`. `filename` should be a filename not a path.

I created something similar which doesn't have this issue:
https://github.com/timfish/sentry-rust-minidump

**Comment by italiks** [comment]
@timfish Thanks for the answer! You are right after changing parameter to a file name everything works
