### ISSUE TITLE
#[must_use] for sentry::init?

### ISSUE THREAD

**Issue by hynek** [getsentry/sentry-rust#57]
`sentry::init` returns a guard and is pointless if it’s not used…ask me how I found out. ;)

ISTM like the 1.27 feature of `#[must_use]` would be *ideal* for it. I’d cook up a PR but looking at Travis it seems like y’all are checking against old rustc versions and I’m not sure if there’s a backward-compatible way to use it?

**Comment by mitsuhiko** [comment]
I was thinking about it but it's safe to not use if you call drain on the hub manually. But yeah, I might be in favor of this.

**Comment by mitsuhiko** [comment]
This is now done as part of #81
