### ISSUE TITLE
Apply Scope Modifications To Transactions

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-rust#575]
Currently, any scope configurations such as set_user or set_tag only apply to Error Events for the Rust SDK. We should implement this for transactions as well.

<img width="885" alt="Screenshot 2023-05-15 at 12 14 30 PM" src="https://github.com/getsentry/sentry-rust/assets/96670625/7d73d6fb-422d-46b7-a2b1-a6488399b1d0">

**Comment by hobofan** [comment]
It looks like this has been partially implemented in https://github.com/getsentry/sentry-rust/pull/590.

It works for me with `set_tag` now, but the values for `set_user` still don't propagate as far as I can tell.
