### ISSUE TITLE
Ureq always added as dependency

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry-rust#581]
### Environment

0.30.0+

### Steps to Reproduce

1. Create an empty crate
2. Add `sentry` as sole dependency with default features enabled

### Expected Result

`ureq` is not added as dependency (see Cargo.lock)

### Actual Result

`ureq` is pulled in.

**Comment by Swatinem** [comment]
Seems to be a bug in cargo itself: https://github.com/rust-lang/cargo/issues/10801

I tried to reproduce, and I can confirm that it is indeed present in `Cargo.lock`, but it is not being built or linked.
