### ISSUE TITLE
Default to grouping by Rust panic and not exception

### ISSUE THREAD

**Issue by bfpepper87** [getsentry/sentry-rust#582]
When working with Rust issues, can we make it default to unwind to the panic and group by that as opposed to grouping by the exception?

**Comment by Swatinem** [comment]
What exactly do you mean by "grouping by exception"? Also, what is your expectation here?

The panics are grouped by the stack trace by default, and not by the panic message.

**Comment by stephanie-anderson** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
