### ISSUE TITLE
Weekly CI notifications

### ISSUE THREAD

**Issue by flub** [getsentry/sentry-rust#583]
Hello, it appears I still get notifications when weekly CI fails, e.g.: https://github.com/getsentry/sentry-rust/actions/runs/5040379062

See https://github.com/getsentry/rust-sourcemap/issues/57 for earlier precedent of how to handle this.

**Comment by Swatinem** [comment]
Thats weird, you literally never touched that file:
https://github.com/getsentry/sentry-rust/commits/master/.github/workflows/weekly.yml

I have no idea why you are getting notifications, I never ever receive ones for actions, but okay, I have that disabled completely in my notification settings:

![Bildschirmfoto 2023-05-23 um 10 13 49](https://github.com/getsentry/sentry-rust/assets/580492/bd91d7ff-04bf-41ee-9412-848889b57dee)

**Comment by flub** [comment]
Oh, that's a option you can turn off?  Thanks!  I've switched it off now :smile: 

Indeed strange why github decides to email me if I never touched this, I just assumed I did because I did get emails... oh well.  Feel free to close if you don't want to take any further action.

**Comment by Swatinem** [comment]
I don’t know what action I can take tbh? Renaming the file once, and then renaming it back in a different PR? But as you have never touched that file, not sure if it will help either.

But as you said you have now switched off workflow notifications completely, I might as well close this :-)
