### ISSUE TITLE
Does `traces_sample_rate` affect breadcrumb reporting from `tracing::info`?

### ISSUE THREAD

**Issue by ferologics** [getsentry/sentry-rust#608]
it's recommended to reduce `traces_sample_rate` in production builds to a lower than `1.0` value
```
#[cfg(debug_assertions)]
traces_sample_rate: 1.0,
#[cfg(not(debug_assertions))]
traces_sample_rate: 0.1,
```
my question is, will all the `tracing::info!("breadcrumb");` invocations be reported in sentry issues? or will only `0.1` of them be passed through?

**Comment by Swatinem** [comment]
`traces_sample_rate` only has an effect on capturing performance transactions. It should not have any effect on the tracing integration itself, and `info!()` and `error!()` logs should still be captured regardless.
