### ISSUE TITLE
Breadcrumbs from Multiple Requests Mixing in Sentry Traces

### ISSUE THREAD

**Issue by ferologics** [getsentry/sentry-rust#616]
We're using `sentry-rust` with Actix-web and the `tracing` integration. We've encountered an issue where Sentry traces for errors contain breadcrumbs from multiple incoming requests. Our goal is to ensure that breadcrumbs are associated only with the specific request that generated them, similar to the behavior of [tracing-actix-web](https://github.com/LukeMathWalker/tracing-actix-web).

We've considered using `sentry-actix`, but we want finer control over error reporting and prefer sending errors via `tracing::error!()`.

One approach we've looked into is creating a custom middleware to manage the Sentry hub and scope across threads. However, this feels somewhat manual and might not be the most efficient solution.

Is there a recommended or more streamlined way to achieve isolated breadcrumbs per request without relying on `sentry-actix`'s automatic error reporting?

**Comment by Swatinem** [comment]
You should be able to turn of automatic error capturing with the builder methods, like so:

```rust
sentry_actix::Sentry::builder().capture_server_errors(false).finish()
```

That should give you Hub isolation and more metadata on the scope for each request, as well as the option to start a performance monitoring transaction with `start_transaction(true)`.
