### ISSUE TITLE
Propagate tracing span attributes in sentry events

### ISSUE THREAD

**Issue by samscott89** [getsentry/sentry-rust#617]
Hey,

Thanks for providing Rust support. We're happily using `sentry` and `sentry-tracing` crates. Mostly all working well.

We expose a ton of helpful debugging information through span attributes. As far as I can tell, these are captured for performance monitoring, but aren't provided as context when capturing events (via `tracing::error!` for example).

Is there any way that any span data captured could also be included in events emitted by `sentry-tracing`?

**Comment by Swatinem** [comment]
I don’t think this is currently possible. Other members of the team are prototyping ways to rewamp the performance monitoring / tracing APIs to make such things easier in the future, but it is still very early in that process.

**Comment by samscott89** [comment]
Cool, looking forward to seeing what happens there. Let me know if you want any feedback/testers, we'd be open to trying stuff out.

**Comment by tsionyx** [comment]
Hello. I just [made the implementation](https://github.com/getsentry/sentry-rust/pull/629) of this feature. Would be glad if someone looks at it and maybe suggest some improvements.

**Comment by thomaseizinger** [comment]
Unfortuantely, this feature appears to be tied to a `span_filter` that records the span which in turn might spam many spans to Sentry's Tracing feature. It would be great if we can record fields from spans in breadcrumbs while at the same time, only submit certain spans to Sentry.

**Comment by thomaseizinger** [comment]
> It would be great if we can record fields from spans in breadcrumbs while at the same time, only submit certain spans to Sentry.

The way to achieve this is to use a `span_filter` that allows all spans, paired with a `traces_sampler` that inspects the current span and computes an appropriate sampling rate (i.e. 0.0 for discard or 1.0 for include).
