### ISSUE TITLE
Breaking (integration) as of actix-web 0.7.x

### ISSUE THREAD

**Issue by ryanmcgrath** [getsentry/sentry-rust#63]
A cursory glance indicates the `'static` lifetime for the middleware definition doesn't sit well with `actix-web <= 0.7`. I took a quick stab at fixing it but didn't wanna mess around with the `hub` stuff, since that's pretty far out of my understanding of the library 5000 feet level.

**Comment by mitsuhiko** [comment]
The latest 0.2.0 version of the integration supports 0.7 now.

**Comment by ryanmcgrath** [comment]
Awesome, thanks!
