### ISSUE TITLE
change backtrace_support to public

### ISSUE THREAD

**Issue by damody** [getsentry/sentry-rust#64]
In info report we need backtrace information. but default is close.
```rust
sentry::capture_event(Event {
        message: Some("Hello test!".into()),
        level: Level::Info,
        stacktrace: current_stacktrace(),
        ..Default::default()
    });
```
so, I can't write like it.

**Comment by damody** [comment]
https://github.com/getsentry/sentry-rust/blob/3abc37eaaf49ff6758d649da04d77def29e1d184/src/hub.rs#L336

and capture_message also need the stacktrace.

**Comment by mitsuhiko** [comment]
We should make the `capture_message` backtrace attaching a configurable option in addition. Some other SDKs already have that.

**Comment by mitsuhiko** [comment]
For the record `current_stacktrace` is already public in the utils module.

**Comment by damody** [comment]
thanks your respond.
