### ISSUE TITLE
Rust Tracing integration results in panic in application

### ISSUE THREAD

**Issue by hanishgogada** [getsentry/sentry-rust#664]
### Environment

Sentry-rust version 0.3.2

### Steps to Reproduce
1. Enabled traces_sample_rate in ClientOptions
2. Added tracing subscriber using
```
tracing_subscriber::registry()
.with(tracing_subscriber::fmt::layer())
.with(sentry_tracing::layer())
.init();
```
3.Enabled tracing on rust methods through #[tracing::instrument]

### Expected Result

Expected to receive the traces in the console
### Actual Result

```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/util.rs:91:14
failed to set global default subscriber: SetLoggerError(())
```

**Comment by Swatinem** [comment]
This does not seem to be related to Sentry at all, but rather to `tracing(_subscriber)` usage.
Please see the docs for [`init`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/util/trait.SubscriberInitExt.html#method.init), in particular:

> This method panics if a global default subscriber has already been set, or if a log logger has already been set (when the “tracing-log” feature is enabled).

I believe you are running into that problem.
