### ISSUE TITLE
Sentry Install instructions For Rust not Working

### ISSUE THREAD

**Issue by nakul1010** [getsentry/sentry-rust#689]
### Environment

MacOs
rust version: `rustc 1.82.0-nightly (2cbbe8b8b 2024-07-28)`

### Steps to Reproduce
- Create a new project with Rust as platform 
- Follow the install instructions to configure the rust SDK to emit a panic
My code:
```rust
fn main() {
    let _guard = sentry::init(("https://xxxx", sentry::ClientOptions {
        release: sentry::release_name!(),
        ..Default::default()
    }));
    let uid = sentry::capture_message("Something went wrong", sentry::Level::Info);
    println!("uid: {:#?}",uid);

    // Sentry will capture this
    panic!("Everything is on fire!");
}
```

The output: 
```
uid: f6c7e332-xxxx-xxxx-xxxx-xxxxxxxxxxxx
thread 'main' panicked at app/src/main.rs:541:5:
Everything is on fire!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected Result

The panic should be visible in issues section 

### Actual Result

The panic is not visible in issue section of sentry project. 

`Note`: It was working until yesterday. I also tried to create a new project but the same issue is popping up.

**Comment by nakul1010** [comment]
ohh, I can see some of my previous transactions now, but the issue is that they're showing up almost an hour after the transaction was initiated. 
Is there any parameter/field I need to set to get issues instantly on dashboard?

**Comment by stephanie-anderson** [comment]
Hey @nakul1010 - please excuse the late reply on this issue. It can take a few minutes for issues to show up on the board. I hope you haven't experienced any delays on top of that since you opened that issue. 

I will close the issue for now, but please feel free to reopen it, if you still think that something's off 🙏
