### ISSUE TITLE
Unknown backtraces when using sentry-anyhow

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry-rust#707]
### Environment

Using SaaS Sentry, sentry-rust version 0.34.0 and anyhow version 1.0.93.

### Steps to Reproduce

Minimal repro code shared [here](https://github.com/miikka-oura/where-is-sentry-backtrace).

### Expected Result

The resulting event should have a backtrace.

### Actual Result

The resulting event has one unknown frame with the message "This frame has an unknown problem and could not be symbolicated".
![Image](https://github.com/user-attachments/assets/69f30ace-2383-470e-8369-646d08a56920)

Sentry event links are provided in [the shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2349).

**Comment by szokeasaurusrex** [comment]
@InterstellarStella I was unable to reproduce this exact behavior, but I think the most likely explanation is that the user did not upload debug files for their code. They can upload debug files using `sentry-cli debug-files upload`. We should probably surface this better in the Sentry Rust SDK docs
