### ISSUE TITLE
Incorrect backtrace in Windows.

### ISSUE THREAD

**Issue by Frodo45127** [getsentry/sentry-rust#71]
I've been testing Sentry in Linux and Windows and in Windows I receive a completely different backtrace than the one I should receive. This is what I got when my program crashes on Linux:
![imagen](https://user-images.githubusercontent.com/15714929/44613952-3108a180-a81c-11e8-8994-dc8559b33402.png)

And this is what I got on Windows:

![imagen](https://user-images.githubusercontent.com/15714929/44613957-4b427f80-a81c-11e8-8810-ae42fc55d0ea.png)

Both versions use the exact same code, and both have debug symbols included. Also, `RUST_BACKTRACE=1` is set in both operating systems. Is there something special that has to be done on Windows to get it working in the same way as on Linux?

EDIT: In case it helps, this is the entire sentry code of my program:
``` Rust
    // Initialize sentry, so we can get CTD and thread errors reports.
    let _guard = sentry::init((SENTRY_DSN, sentry::ClientOptions {
        release: sentry_crate_release!(),
        ..Default::default()
    }));

    // If this is a release, register Sentry's Panic Handler, so we get reports on CTD.
    if !cfg!(debug_assertions) { register_panic_handler(); }
```

**Comment by mitsuhiko** [comment]
The backtrace is provided from the underlying backtrace that we get from rust or backtrace-rs. There is nothing we can fix here sadly. You should report this against rust itself.
