### ISSUE TITLE
Documentation doesn't build (and the link from crates.io is broken)

### ISSUE THREAD

**Issue by vorner** [getsentry/sentry-rust#92]
According to docs.rs, setry fails to build and therefore it is missing the documentation.

https://docs.rs/crate/sentry/0.12.0

**Comment by jan-auer** [comment]
This is due to a known bug in docs.rs, which does not support certain newer rust features we require in this crate. You can see the documentation for the latest version hosted on https://getsentry.github.io/sentry-rust
