### ISSUE TITLE
Client should implement `RefUnwindSafe`

### ISSUE THREAD

**Issue by Diggsey** [getsentry/sentry-rust#94]
All types implementing `Sync` should also implement `RefUnwindSafe` (because `Sync` types must inherently be unwind safe).

The sentry client is not currently unwind safe, because it stores a trait object of type `Fn(Breadcrumb) -> Option<Breadcrumb> + Sync + 'static` (note the lack of a `RefUnwindSafe` bound).

Any trait object with a `Sync` bound should also have the `RefUnwindSafe` bound, which (assuming the client doesn't store any other unwind-unsafe things) should make it automatically gain the `RefUnwindSafe` implementation.

**Comment by mitsuhiko** [comment]
Not sure if adding `RefUnwindSafe` on the trait bound is a good idea because barely anyone implements it. At the same time just implementing `RefUnwindSafe` on the client sounds like a bad idea. Not sure what to do here.

**Comment by Diggsey** [comment]
You could also wrap the `Box<Fn(...)>` in an `AssertUnwindSafe` (since you already have the `Sync` bound)

**Comment by mitsuhiko** [comment]
Since the box is part of the public API I cannot do that now. What I can do is just making the container of it implement `UnwindSafe` (`ClientOptions`).
